.gitignore
.travis.yml
scripts/travis-build.sh
scripts/travis-test.sh

I've tested this configuration on my own fork, and it seems to work.  I've also set up the gap-packages repository so that it should run Travis tests on any snapshot that contains a `.travis.yml` file, like this one.
If we're lucky, this pull request should be tested automatically and should show up on this page.  Note that it will show up as **failing**, since one manual example is still broken.
After this pull request is merged and everything works, I'll make another one for `stable-2.7`.

Travis CI system support

---

.travis.yml
scripts/travis-build.sh

This change cuts about 10 minutes off every Travis build by getting an updated system GMP from an external APT repo.  It should make Travis much more usable.
Note that Travis is still failing due to GAP changes which have not yet made it to the GAP `master` branch.

Travis now uses system GMP 6.0 from APT

---

.travis.yml
scripts/drone.sh
scripts/travis-build.sh
scripts/travis-test.sh

This should run all tests in `SemigroupsTestAll` and `SemigroupsTestManualExamples`.  Travis tests should be passing at the moment.  They currently work using the `master` branch of GAP, but we should add further checks for `stable-4.8`.

Travis setup for stable-2.7 branch

---

gap/attributes.gi
tst/attributes.tst
tst/testinstall.tst

IrreundantGeneratingSubset behaves incorrectly when given a
semigroup whose generating set consists of a single repeated
element.
Resolves: #160

Fix IrredundantGeneratingSubset in stable-2.7 (Issue #160)

---

gap/attributes/attributes.gi
tst/standard/attributes.tst
tst/testinstall.tst

IrreundantGeneratingSubset behaves incorrectly when given a
semigroup whose generating set consists of a single repeated
element.
Resolves: #160

Fix IrredundantGeneratingSubset in unstable-3.0 (Issue #160)

---

.travis.yml
scripts/travis-build.sh

Travis now runs the test suite 8 times, i.e. every combination of 3 variables:
* 64-bit/32-bit compile
* `master`/`stable-4.8` version of GAP
* `gcc`/`clang` compiler
The version numbers of all required packages are set once each, in `.travis.yml`, for easy editing.

Run Travis tests with more setups

---

.travis.yml
scripts/travis-build.sh
tst/freeband.tst

This brings the Travis tests for `stable-2.7` in line with the tests for `unstable-3.0`.  It now runs all the tests with the `stable-4.8` and `master` branches of GAP, and it does the compilation with both gcc and clang.
For interest's sake, I also included a configuration for **GAP and its packages compiled in 32-bit mode**.  Since Semigroups 2.7 isn't compiled I assumed it would make no difference, but it looks like there are two tests that fail, which seem to be related to **orb**:
```
reading /home/travis/build/mtorpey/gap/pkg/semigroups/tst/freeband.tst . . .
########> Diff in /home/travis/build/mtorpey/gap/pkg/semigroups/tst/freeband.t\
st:185
HTAdd(ht, new, true);
33159
35014
########
########> Diff in /home/travis/build/mtorpey/gap/pkg/semigroups/tst/freeband.t\
st:190
ht;
<tree …
```

Travis: test more configurations with stable-2.7

---

gap/reesmat.gi
tst/reesmat.tst
tst/testinstall.tst

`MatrixEntries` fails for some Rees 0-matrix semigroups whose
matrices contain `0`, since MatrixEntries removes duplicates and
sorts using `Union`, however `0` is not comparable with all
semigroup elements.
This issue is resolved by using `Unique` to remove duplicates,
but not sorting the list of matrix entries.
Resolves: #164

Fix MatrixEntires in stable-2.7 (Issue #164)

---

gap/semigroups/semirms.gi
tst/standard/semirms.tst
tst/testinstall.tst

MatrixEntries fails for some Rees 0-matrix semigroups whose
matrices contain 0, since MatrixEntries removes duplicates and
sorts using Union, however 0 is not comparable with all
semigroup elements.
This issue is resolved by using Unique to remove duplicates,
but not sorting the list of matrix entries.
Resolves: #164

Fix MatrixEntires in unstable-3.0 (Issue #164)

---

gap/congruences/congsimple.gi
gap/congruences/conguniv.gd
gap/congruences/conguniv.gi
tst/standard/conguniv.tst

For technical reasons, ever since Rees 0-matrix semigroup congruences by linked triple were implemented, `IsUniversalSemigroupCongruence` has been a **category** which contains only objects created explicitly by the function `UniversalSemigroupCongruence(S)`.  Therefore we had the situation where a congruence (say by generating pairs or by linked triple in an RMS) might turn out to be universal, but would not satisfy this filter.
`IsUniversalSemigroupCongruence` has now been changed to a **property**, which can be tested, and will return `true` iff a congruence has precisely one congruence class.  Methods intended for universal congruences will then be selected if possible, reducing work done.

Make IsUniversalSemigroupCongruence a property

---

.travis.yml
doc/attributes.xml
scripts/travis-build.sh
tst/standard/grpperm.tst
tst/standard/semibipart.tst
tst/standard/semiboolmat.tst
tst/standard/semifp.tst
tst/standard/semipbr.tst
tst/standard/semirms.tst
tst/standard/semitrans.tst

Currently, the Travis tests in the `unstable-3.0` branch all fail, due to us relying on GAP changes in James' `fix-semi-iso` branch which has not yet been merged into the official GAP repo.  In the long-term we should only test against official GAP versions, but for the moment it's difficult to tell whether new changes we make are causing new problems without any effective automated testing.
This pull request adds another configuration to Travis, which *additionally* runs the tests under `fix-semi-iso`.  Tests under the other branches still fail, but if you want to see whether new changes are alright, you can look at the Travis build page, and you're looking for **two green ticks** to indicate that Semigroups at least works with the altered GAP.
`semipbr.tst` was still failing due to a …

Travis: run tests in GAP branch fix-semi-iso

---

.travis.yml

There are new versions of certain packages available, and Travis should use them.

Travis package versions updated (2.8)

---

.travis.yml

There are new versions of certain packages available, and Travis should use them.
Builds were also reordered for easier readability on the Travis page.
I was going to push this straight to the gap-packages repo as we discussed (it being a trivial change) but it seems that `unstable-3.0` is a protected branch - hence this pull request.

Travis package versions updated (unstable-3.0)

---

scripts/travis-build.sh
scripts/travis-test.sh

The full log produced by Travis CI is verbose and unwieldy. If the build fails it can take a long time to figure out what's going wrong.
This pull request just adds some extra commands to the build and test scripts which "fold" the Travis output, i.e. collapse certain sections so that they can be expanded by a click. A successful test should display on just one or two screens, and a failing test should be much easier to diagnose.
Have a look at the Travis output for this PR to see how it looks in action.

Travis: add log-folding (2.8)

---

scripts/travis-build.sh
scripts/travis-test.sh

The full log produced by Travis CI is verbose and unwieldy.  If the build fails it can take a long time to figure out what's going wrong.
This pull request just adds some extra commands to the build and test scripts which "fold" the Travis output, i.e. collapse certain sections so that they can be expanded by a click.  A successful test should display on just one or two screens, and a failing test should be much easier to diagnose.
Have a look at the Travis output for this PR to see how it looks in action.

Travis: add log-folding (3.0)

---

.travis.yml

Travis is having some issues with some of its APT servers.  The new and up-to-date versions of clang++ which we require have been taken down and are not currently available without some hacking.
This pull request removes clang tests - Travis will just use gcc for now.
See these links for more detail: [1](https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540) [2](http://lists.llvm.org/pipermail/llvm-foundation/2016-May/000020.html)

Travis: remove clang tests

---

.travis.yml

Travis is having some issues with some of its APT servers. The new and up-to-date versions of clang++ which we require have been taken down and are not currently available without some hacking.
This pull request removes clang tests - Travis will just use gcc for now.

Travis: remove clang (stable-2.8)

---

src/gap.cc
src/ufdata.hh

This should make it possible to save `UFData` objects and reload them with `SaveWorkspace` and `LoadWorkspace`.
I haven't been able to test it properly, since I get a segfault any time I try to use `SaveWorkspace` (even before these changes).

UFData: add SaveWorkspace and LoadWorkspace support

---

.gitignore
scripts/travis-test.sh
tst/workspaces/load-workspace.tst
tst/workspaces/save-workspace.tst

This pull request adds a new test system to the automatic Travis tests, to allow objects to be saved to a workspace which is then reloaded.  There is a new `tst/workspaces` directory with two new files, `save-workspace.tst` and `load-workspace.tst`, which create objects and then verify that the objects exist after loading.
`travis-test.sh` now has an extra section where it:
* creates a new session
* runs `save-workspace.tst`
* saves the workspace to a file
* ends the session
* reloads the workspace from the file
* runs `load-workspace.tst`
* deletes the workspace file
I have included tests for the UFData object as an example.  New tests should be added for any other C/C++ objects we have created, and this can be done easily by adding new test blocks to those files.

SaveWorkspace: add tests to Travis

---

gap/congruences/congrees.gi

This is no longer used anywhere, and it's not clear what `One` should mean for a congruence class anyway.

Delete redundant OneImmutable code for congruence classes

---

doc/display.xml

I noticed that the documentation for `DotString` twice included the text `opts.number` when it should have said `opts.normal`. I've fixed this.

Correct DotString doc for the 'normal' option

---

gap/semigroups/semitrans.gi
tst/standard/semitrans.tst

This PR addresses Issue #192 by comparing the size of the semigroup (if known) to the degree of the transformation semigroup in `RepresentativeOfMinimalIdeal`, and doing `TryNextMethod` if appropriate.
I also check for the degree of the transformation semigroup (regardless of the size of the semigroup). If the degree is greater than some fixed number, we determine that the algorithm will take too long in any circumstance, and so we may as well try the next method. This requires a somewhat arbitrary decision for what that number should be - I went with degree  10,000 as the limit.

Make RepresentativeOfMinimalIdeal check for high degree (Issue #192)

---

gap/elements/ffmat.gi
gap/greens/greens-generic.gi
gap/hash.gd
gap/hash.gi
gap/semigroups/semiffmat.gd
tst/standard/greens-generic.tst
tst/standard/semiffmat.tst
tst/standard/semirms.tst

Remove unused hash functions, fix hash functions for matrices and row bases,
make sure that IsMatrixSemigroup implies IsFinite (since IsMatrixSemigroup =
IsMatrixOverFiniteFieldSemigroup), add some tests.
Resolves Issues #210 and #211.

Replace hash function for IsPlistMatrix/RowBasisOverFiniteFieldRep

---

gap/greens/greens-inverse.gi
tst/testinstall.tst

There was a bug in the \in method for L-class of inverse-op semigroups,
which meant that it returned incorrect results. This is resolved in the PR. 
This bug seems to have been in the code for a while (over a year at least).

Resolve Issue #217

---

doc/z-chap15.xml
gap/attributes/maximal.gi
tst/extreme/maximal.tst
tst/standard/maximal.tst

The maximal subsemigroups of a regular Rees 0-matrix semigroup
over a group are described as one of 6 possible types. I have updated
the ordering in the documentation, and consequently the code, so that
the ordering agrees with the ordering as they are described in the paper
by DMW (Donoven, Mitchell, Wilson).

Re-order the types of a maximal subsemigroup

---

gap/congruences/congpairs.gi
tst/standard/congpairs.tst

Such a method didn't exist, and GAP was using a crazy method from the library to calculate the information.

Add EquivalenceRelationPartition method for finite congruences by generating pairs rep

---

gap/congruences/quotients.gi
tst/standard/quotients.tst
tst/testinstall.tst

The current library method uses `Print` on the congruence and the semigroup, meaning that it regurgitates all the generating pairs and semigroup generators all over the screen, which creates an unreadable mess.
This method uses `ViewObj` on the congruence, giving something like
```
<quotient of <semigroup congruence over <transformation semigroup of degree 3 with 2 generators> with 1 generating pairs>>
```
which is much more readable.
Note that we also don't display the parent semigroup in the form "<quotient of `S` by `cong`>" but rather only "<quotient of `cong`>", since the `ViewObj` method for a congruence specifies what semigroup it's defined over anyway, and we don't want the semigroup printed twice.

Add a reasonable ViewObj method for quotient semigroups

---

gap/main/setup.gi
tst/standard/semirms.tst

Hashing RZMS elements over pc groups would fail; this replaces the hashing method with a more robust system. There is an arbitrary choice of primes in the hashing method; these were chosen because they seem to work well for avoiding collisions.
This follows on from #195

Fixes a bug with hashing RZMS elements over certain semigroups.

---

gap/congruences/conginv.gi

The problem was related to the removal of `GenericSemigroupData`.  We used to have `idsdata := GenericSemigroupData(idsmgp)`, and then we'd look up positions in `idsdata`.  Sensibly, we've removed the line where we set `idsdata`, but it was still trying to look things up in it.
I've now removed the variable, and we just look things up **in the semigroup itself**, using `Position(idsmgp, x)` and so on, which I understand is now the way we do things.

Fix broken conginv.tst

---

gap/attributes/maximal.gi
tst/standard/maximal.tst
tst/testinstall.tst

After carefully stepping through the code with a failing example, I identified a single incorrect line in the code for `MaximalSubsemigroups` for a Rees 0-matrix semigroup which intersect every H-class and contain a given set of elements. Essentially I was creating an element as `x * y` rather than `y * x`.
I also took this opportunity to use the variable name `zero` instead of `Z`, since apparently `Z` is already defined in GAP and is (should be?) read only.

Fix issue #230: MaximalSubsemigroups

---

doc/cong.xml
doc/z-chap19.xml

A few operations for left and right congruences (essentially synonyms for equivalence versions) weren't documented.

Left/right congruences: add missing doc

---

gap/congruences/congpairs.gi
tst/standard/congpairs.tst

Modify `EquivalenceRelationPartition` so that it excludes non-trivial classes, to match the definition in the GAP library.

Change EquivalenceRelationPartition to match documentation

---

doc/cong.xml
gap/congruences/cong.gi
gap/congruences/congrees.gi
tst/standard/cong.tst
tst/standard/congpairs.tst
tst/standard/congrees.tst

`EquivalenceRelationLookup` and `EquivalenceRelationCanonicalLookup` now have methods for generic congruences.  This allows us to compare congruences of different types, and to compare their classes (a test which is readded here, having been unwisely removed a few commits ago).
Doc and tests are adjusted, and a few other little features are added.

Add Lookup and CanonicalLookup methods for generic congruences

---

gap/greens/gren.gi

I just made a pull request in Digraphs which changes the name of `OutNeighboursCopy` to `OutNeighboursMutableCopy`.  This change keeps compatibility between the two packages.

Rename OutNeighboursCopy to OutNeighboursMutableCopy (digraphs)

---

doc/properties.xml
doc/semiex.xml
gap/obsolete.gd
gap/obsolete.gi
gap/semigroups/semiex.gd
tst/standard/properties.tst

They're monoids, so for consistency with the other standard examples, we should call them monoids.
The previous names are now in `obselete.g*`.

Rename *FactorisableDualSymmetricInverseSemigroup to *FactorisableDualSymmetricInverseMonoid

---

doc/bipart.xml
gap/elements/bipart.gd
gap/elements/bipart.gi
tst/standard/bipart.tst

This addresses a card from Trello.
A partial perm bipartition naturally defines a partial perm, and a partial perm can be converted into a block bijection in a nice way (via a monoid embedding). Thus we should be able to convert partial perm bipartitions to block bijections in this way.
I believe that the resulting conversion is indeed a monoid embedding.

Add operation to convert a partial perm bipartition to a block bijection

---

doc/properties.xml
gap/attributes/attr.gi
gap/attributes/properties.gd
gap/attributes/properties.gi
tst/extreme/examples.tst
tst/standard/cong.tst
tst/standard/properties.tst
tst/standard/semiex.tst

Previously `IsSemigroupWithCommutingIdempotents` was a synonym for `IsBlockGroup`. This was mathematically incorrect.
A semigroup with commuting idempotents is necessarily a block group, but the converse is not necessarily true.

Fix IsSemigroupWithCommutingIdempotents

---

doc/semitrans.xml
doc/z-chap15.xml
gap/obsolete.gd
gap/obsolete.gi
gap/semigroups/semitrans.gd
gap/semigroups/semitrans.gi
tst/standard/obsolete.tst
tst/standard/semitrans.tst

`SEMIGROUPS.GraphOfActionOnPairs` is now a Digraph, and is called `DigraphOfActionOnPairs`.
`IsSynchronizingSemigroup` and `RepresentativeOfMinimalIdeal` were the only methods which used it. These have been updated.

Make GraphOfRightActionOnPairs a digraph object

---

.covignore
.travis.yml
gap/main/setup.gi
scripts/travis-build.sh
scripts/travis-coverage.py
scripts/travis-test.sh
tst/standard/setup.tst

In Issue #171, @james-d-mitchell suggests adding code-coverage checking and lint checking to out Travis setup. I think these are both good intentions.
After this PR, Travis downloads the gaplint tool. After running the normal GAP tests and the saved workspace tests, Travis now runs a linting check. **We should discuss what the linter should be run on, and what we should do when we encounter trouble.**
Currently I've got it doing `gaplint.py gap/*/*.gi`, and failing the Travis instance if _anything_ goes wrong. This checks the linting of the `.gi` files which reside in a subdirectory of the `gap` subdirectory of the package.
Today I spent a good chunk of time linting the Semigroups package and fixing the gaplint tool so that, at least in `unstable-3.0`, running `gaplint.py gap/*/*.gi` …

Use gaplint and code-coverage in the Travis tests

---

gap/attributes/attr.gi
gap/attributes/attrinv.gi
gap/attributes/properties.gi
gap/semigroups/semirms.gi
tst/standard/attr.tst
tst/standard/attrinv.tst
tst/standard/properties.tst
tst/standard/semirms.tst
tst/testinstall.tst

This PR addresses Issue #253 and makes some small improvements.
The default `IsIdempotentGenerated` method, given a semigroup `S`, first checks where the "generators" of `S` are idempotents. That's a good idea for semigroups and semigroup generating sets, but for ideals it was using the ideal generating set. Therefore I've replaced `Generators` by `GeneratorsOfSemigroup`.
I've added another check here, for monoids. The only elements of a monoid which can be multiplied together to produce an element of the group of units are themselves units. Since the only unit which is an idempotent is the identity, and since the subsemigroup generated by the identity is trivial, the idempotent generated subsemigroup of a monoid has a trivial group of units. Therefore, for a monoid to be idempotent …

Fix Issue #253 (IsIdempotentGenerated)

---

gap/semigroups/semirms.gi
tst/standard/semirms.tst

This PR resolves issue #264.
Let `R` be a Rees 0-matrix semigroup and let `U` be a subsemigroup of `R`. To check whether `U` had a multiplicative zero, the code previously essentially returned `true` if and only if `U` contained the special `0` element of `R`.
However, there is more to it than this. If `U` doesn't contain the `0` element of `R`, then it still might contain a multiplicative zero. If `U` contains elements from multiple rows or columns of `R`, then (fairly obviously) it can't have a multiplicative zero. I have added code to check this case. Otherwise, when `U` contains elements all from the same row and column `R`, there is more work to be done. I have added a `TryNextMethod` at the end of the function to handle this case - it will use the more general `MultiplicativeZero` …

Fix issue #264 (MultiplicativeZero for RZMS)

---

Makefile.am

This causes things to be linked properly together on my PC, as described in [libsemigroups issue #25](https://github.com/james-d-mitchell/libsemigroups/issues/25).

makefile: add libsemigroups/util/uf.cc to SOURCES

---

gap/congruences/conglatt.gi
tst/standard/conglatt.tst

@james-d-mitchell found a problem when using `LatticeOfCongruences`, which looked like this:
```gap
gap> LoadPackage("smallsemi", false);;
gap> S := AsSemigroup(IsTransformationSemigroup, SmallSemigroup(5, 11));;
gap> LatticeOfCongruences(S);
Error, UniteSet: <set1> must be a mutable proper set (not a list (plain,hom,nsort)) in
UniteSet( I, AsSSortedList( C2 ) ); at /home/mtorpey/gap/lib/coll.gi:2573 called from 
Union2( tounite[1], tounite[2] ) at /home/mtorpey/gap/lib/coll.gi:2764 called from
Union( PreImagesRange( map1 ), PreImagesRange( map2 ) ) at /home/mtorpey/gap/lib/mapping.gi:1420 called from
...
```
It turns out this isn't to do with the lattice code, but an issue with smallsemi and `AsSemigroup` which I've now made into Issue #269.  However, I was surprised to see that so much …

conglatt: avoid extra work in BlistList

---

gap/congruences/cong.gd
gap/congruences/cong.gi
gap/congruences/congfpmon.gi
gap/congruences/conginv.gi
gap/congruences/conglatt.gi
gap/congruences/congpairs.gi
gap/congruences/congrees.gi
gap/congruences/congrms.gi
gap/congruences/congsimple.gi
gap/congruences/conguniv.gi
src/congpairs.cc
src/congpairs.h
src/pkg.cc
tst/standard/cong.tst
tst/standard/congfpmon.tst
tst/standard/conginv.tst
tst/standard/congpairs.tst
tst/standard/congrees.tst
tst/standard/congrms.tst
tst/standard/congsimple.tst
tst/standard/conguniv.tst

**tldr: this is a "no checks" version of `\in` for congruences.**
We want to be able to use
```gap
[x, y] in cong;
```
to check whether a pair is in a congruence.  Previously, we have had a different `\in` method for each type of congruence, which checks input and then does the appropriate thing.  However, we want to be able to call these methods without doing checks first, and even without constructing lists (which is also an overhead).
This PR replaces all the `\in` methods with methods for `CongruenceTestMembershipNC`, a new operation which takes three arguments `cong, elm1, elm2` and returns true iff `elm1` and `elm2` are congruent with respect to `cong`.  This faster method can now be used when we already know the input is valid (e.g. in `LatticeOfCongruences`, which at the moment is …

Add CongruenceTestMembershipNC

---

doc/attr.xml
doc/semiringmat.xml

`Matrix` and `RandomMatrix` were multiply defined, so I've added labels.
Also fixed a little LaTeX error to do with using `\text`.

doc: multiple labels for Matrix and RandomMatrix functions

---

src/semigrp.cc

This commit resolves Issue #284, as CAJ correctly points out, the
variable pos is already a GAP integer object, and so the `INTOBJ_INT` in
line 1091 was incorrect. I guess this didn't cause any problems because
the result of `INTOBJ_INT(pos)` is usually a large number. The second
argument of the function fropin, which this issue affects, is the limit,
so using a large argument will probably just have enumerated the
semigroup to the end.

kernel: remove incorrect INTOBJ_INT

---

gap/semigroups/semitrans.gi
tst/standard/semitrans.tst
tst/testinstall.tst

This PR resolves Issue #286. This was caused by `IsSynchronizingSemigroup(S, n)` using the operation `DigraphOfActionOnPairs(S, n)`. However, `DigraphOfActionOnPairs(S, n)` only works if the the semigroup acts on `[1 .. n]` (i.e. `S` doesn't move a point within `[1 ..n]` to a point larger than `n`). This wasn't tested in code coverage - but when I added the coverage, we got the inconsistent results, as detailed in the issue.
The idea behind using the `DigraphOfActionOnPairs` was sound, and I've come up with a workaround, but it makes the code a bit more complicated unfortunately.
In this PR, I've also included the improved code coverage that led to me discovering this issue. At the moment, code coverage of `semitrans.gi` in `master` is:
```
semitrans.gi has 97% coverage: 539/555 lines
``` …

Improve code coverage of semitrans and fix bug in IsSynchronizingSemigroup

---

doc/isorms.xml
doc/z-chap01.xml
doc/z-chap05.xml
doc/z-chap17.xml

Once Wilf's standard examples stuff and Chris's matrix stuff is merged in, this should finally mean that there are no errors or warnings in `SemigroupsMakeDoc` (though who knows, maybe one or two!)
A preamble wants to be written for *Isomorphisms of Rees (0-)matrix semigroups*.  I've made a [Trello card](https://trello.com/c/W7jasQ1D/178-doc-add-a-preamble-for-isomorphisms-of-rees-0-matrix-semigroups).

Fix various errors in the doc

---

doc/semitrans.xml
doc/z-chap13.xml
gap/semigroups/semitrans.gd
gap/semigroups/semitrans.gi
tst/standard/semitrans.tst

`DigraphOfActionOnPoints` was undocumented. I've documented it. In the process, I thought it made sense to make it consistent with `DigraphOfActionOnPairs`. Thus the digraph now has edge labels that give the index of the generator that corresponds to an edge.
Due to this, the method takes a small performance hit - we previously added new edges using `AsSet` to avoid creating duplicates, but this sorts the out-neighbours list in a way that makes it impossible to keep track of edge labels. Since the out-neighbours are not sorted, this (harmlessly) changes the output of some tests, with functions that use `DigraphOfActionOnPoints`.

Document and slightly change DigraphOfActionOnPoints

---

doc/z-chap05.xml

When we mention that users should use `RandomSemigroup` for random matrix semigroups, it should be immediately obvious which filter to use: `IsMatrixOverFiniteFieldSemigroup`.
And a couple of other tiny things.

doc: minor matrix semigroups changes

---

tst/extreme/cong.tst

The `SemigroupsTestExtreme()` tests were run. Three issues were found. I have fixed two of them. The third one, in the file cong.tst line 104, is being dealt by Michael.

Fix extreme tests

---

gap/congruences/congpairs.gi
tst/extreme/cong.tst
tst/testinstall.tst

This was caused by a naive assumption in `EquivalenceClasses` - namely that the fp semigroup in question is finite; in fact it might very well be infinite, but might have a finite number of equivalence classes.
This method could be improved further if we introduced a method in libsemigroups which returned a representative for a congruence class - just as we were discussing earlier!  James suggested that he and I might do that next week, and then an even better version of this method could perhaps go into Semigroups 3.1

Fix failing test in extreme/cong.tst

---

gap/congruences/conglatt.gi
tst/standard/conglatt.tst

By stopping relying on the internal representation of the
congruence in the code.

conglatt: fix Issue #309

---

doc/isorms.xml
doc/z-chap17.xml
gap/attributes/isorms.gd
gap/attributes/isorms.gi
tst/standard/isorms.tst

This adds documentation for the actual constructors `R(Z)MSIsoByTriple` and also adds checks to them to make them safe (there's also an `NC` version).

isorms: add checks to code, and document

---

src/semigrp.cc

This allows us to reserve enough memory in the C++ semigroup
associated to a GAP semigroup.

kernel: use reserve when size is known

---

gap/attributes/attr.gi
gap/attributes/maximal.gi
tst/extreme/maximal.tst
tst/standard/attr.tst
tst/standard/maximal.tst

For a regular Rees (0-)matrix semigroup over a group, it's easy to say write down a fairly small generating set for the idempotent generated subsemigroup. For Rees matrix semigroups, I think the method gives a minimal generating set (it's certainly irredundant). For Rees 0-matrix semigroups, the code now makes use of my recent addition to Digraphs called `UndirectedSpanningForest`. A spanning forest of the `RZMSDigraph` corresponds to a generating set for the idempotent generated subsemigroup. Whilst this certainly does not return a irredundant generating set in general, it has the potential to return a much smaller generating set that was obtained previously.
Additionally, this PR allows me to address a long-standing TODO from my maximal subsemigroups code. At a certain part in those …

Install specific IsIdempotentGenerated methods for RMS/RZMS

---

doc/attrinv.xml
gap/attributes/properties.gd
tst/standard/properties.tst
tst/standard/semipperm.tst

A monogenic semigroup is either the monogenic free semigroup, or a finite monogenic semigroup with index `m` and period `r`.
If `S` is monogenic and regular, then it is finite, and moreover it has index `1`. Therefore it is a cyclic group.
I've installed two true methods:
* `IsRegularSemigroup and IsMonogenicSemigroup` => `IsGroupAsSemigroup`
* `IsRegularSemigroup and IsMonogenicSemigroup` => `IsFinite`

Add immediate methods for regular monogenic semigroups

---

tst/standard/attr.tst

I added some tests to `attr.tst` that show the small size of the generating sets now returned by `IdempotentGeneratedSubsemigroup` for a Rees (0-)matrix semigroup over a group.

Add big IdempotentGeneratedSubsemigroup tests

---

gap/attributes/properties.gd
gap/attributes/properties.gi

`IsEUnitaryInverseSemigroup` does not work for some semigroups which don't satisfy
`IsInverseSemigroup`. For example:
```
gap> S := Semigroup([Transformation([2, 2]), Transformation([2, 1, 2]),
> Transformation([3, 3, 2])]);;
gap> IsEUnitaryInverseSemigroup(S);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 2nd choice method found for `IsEUnitaryInverseSemigroup' on 1
arguments at /Users/crussell/gap/lib/methsel2.g:241 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
called from read-eval loop at *stdin*:3
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> quit;
gap> IsInverseSemigroup(S);
false
```

properties: fix IsEUnitaryInverseSemigroup

---

gap/tools/io.gi
tst/standard/io.tst

For some reason, when a file couldn’t be opened fail was displayed in
the error rather than the filename, this commit fixes this, and adjusts the 
tests.

io: fix error messages

---

gap/semigroups/semitrans.gi
tst/standard/semitrans.tst

The problem was that the `One` of the semigroups was used in the
generators instead of the `MultiplicativeNeutralElement`. This PR
fixes this.

Fix issue 342 (direct product of transformation semigroups)

---

doc/semitrans.xml
doc/z-chap06.xml

Currently there is only the GAP library version, which only talks about groups.

doc: add semigroup version of DirectProduct

---

gap/semigroups/semifp.gi
tst/standard/semifp.tst

The internal functions `SEMIGROUPS.WordToExtRepObj`,
`SEMIGROUPS.ExtRepObjToString`, and `SEMIGROUPS.WordToString` are introduced.

Add internal functions for converting words to ext rep obj words and to strings

---

PackageInfo.g
README.md
doc/display.xml
doc/fropin.xml
doc/z-chap13.xml
doc/z-chap18.xml
gap/congruences/conginv.gi
gap/greens/gree.gi
gap/greens/gren.gi
gap/ideals/idealenum.gi
gap/main/fropin.gd
gap/main/fropin.gi
gap/semigroups/grpperm.gi
gap/semigroups/semifp.gi
gap/semigroups/semitrans.gi
gap/tools/display.gd
gap/tools/display.gi
src/fropin.cc
tst/standard/attr.tst
tst/standard/display.tst
tst/standard/fropin.tst
tst/standard/gren.tst

Replace `Left/RightCayleyGraphSemigroup` with `Left/RightCayleyDigraph` and introduce some functions for drawing these objects. This PR requires Digraphs version 0.10.0 which is not yet released, so the tests will probably fail.
These essentially just wrap the value previously returned by
`Left/RightCayleyGraphSemigroup` in a `Digraph` object. Methods for
`Left/RightCayleyGraphSemigroup` continue to exist (just calling
`OutNeighbours(Left/RightCayleyDigraph)` since they are defined in the
library. All other occurrences of `Left/RightCayleyGraphSemigroup` are
replaced with `Left/RightCayleyDigraph`.

Cayley digraphs

---

Makefile.am

This PR introduces a slight change in the build setup to avoid compiler warnings when using libsemigroups 0.3.2.

build: update for changes to libsemigroups

---

gap/main/fropin.gi

Previously we did `Digraph(EN_SEMI_RIGHT_CAYLEY_GRAPH(S))` which involved
copying the output of `EN_SEMI_RIGHT_CAYLEY_GRAPH(S)`, and performing
checks that the output was valid. We make the output of
`EN_SEMI_RIGHT_CAYLEY_GRAPH(S)` immutable, and use `DigraphNC` to avoid
these unnecessary checks. This seems to resolve Issue #356.

Fix issue #356

---

gap/attributes/attract.gi
tst/standard/attract.tst
tst/testinstall.tst

This PR resolves issue #363.
Suppose that we suspect that `e` is the multiplicative neutral element of `S`. The bug was caused by testing whether `e` acts as the identity for all `Generators(S)`. However this isn't sufficient when `S` is an ideal. We need to use `GeneratorsOfSemigroup(S)` instead. I also add a more thorough check before calling `GeneratorsOfSemigroup(S)`, so that we avoid doing it for ideals if we can.

Fix MultiplicativeNeutralElement for ideals

---

gap/semigroups/semieunit.gd
gap/semigroups/semieunit.gi

There is also a change to the comments describing this representation
and a commented out method has been removed in semieunit.gi

semieunit: fix IsMcAlisterTripleSemigroupElementRep declaration

---

gap/attributes/isorms.gi

When the package `AutPGrp` (which is used to calculate automorphisms of p-groups) is loaded, the Semigroups package tests fail. I will explain why in a minute. `AutPGrp` is required by `polycyclic`; it seems reasonable to have this package loaded as well as the Semigroups package, so I think we should do what we can to fix this problem.
In the code for `AutomorphismGroup` of a Rees (0-)matrix semigroup `R` in the Semigroups package, the following happens. The group `aut_group := AutomorphismGroup(G)` is created, where `G` is the underlying semigroup of `R`. Then:
```
hom := NaturalHomomorphismByNormalSubgroupNC(aut_group,
InnerAutomorphismsAutomorphismGroup(aut_group));
```
Without `AutPGrp` loaded, this all works perfectly. However, when `AutPGrp` is loaded, the method for …

Modify AutomorphismGroup for R(Z)MS to accommodate AutPGrp package

---

gap/semigroups/semigrp.gi
tst/testinstall.tst

The `One` of a monoid needs to be in its `GeneratorsOfMagma`, since we don't know (without further work) whether the other elements generate (as a semigroup) the `One`.
Previously this was only done if the generators satisfy `CanEasilyCompareElements` and the `One` isn't already in there. If we can't easily compare elements, we still need to add the `One` if needed. Since it's too expensive to work out whether the `One` is already one of the generators, we should add the `One` regardless.
This resolves #371

Add One to GeneratorsOfMagma if needed in MonoidByGenerators

---

gap/main/fropin.gi
src/bipart.cc
src/semigrp.cc
tst/standard/fropin.tst

This PR updates Semigroups for the release of libsemigroups 0.4.0. The changes are internal only and in the kernel module, and are related to changes in the `Semigroup` object in libsemigroups. I am in the process of releasing libsemigroups 0.4.0 and this PR will probably fail (to compile) until libsemigroups 0.4.0 is actually released. 
The commits in this PR should be squashed when the time comes.

Update for libsemigroups 0.4.0

---

gap/congruences/cong.gi
tst/standard/cong.tst

This commit fixes a diff in GAP's `tst/testinstall/semigrp.tst`, caused by
there being not method for `NrEquivalenceClasses` for some types of
congruences. This commit provides a fallback method for
`NrEquivalenceClasses`.
This addresses part of Issue #395.

Add generic method for NrEquivalenceClasses for a semigroup congruence

---

gap/attributes/attr.gi
tst/testinstall.tst

By `TryNextMethod` in the `StructureDescription` method for `IsGroupAsSemigroup` when the argument is in the category `IsGroup`.

Resolve issue 393

---

tst/standard/semieunit.tst

The usual `gap> SEMIGROUPS.StopTest();` line was missing from `standard/semieunit.tst`. This was causing problems since, by default, `InfoWarning` has level `1` in GAP, but after running this test file, it has level `0`. There are test files in GAP (eg `tst/testinstall/function.tst`) that assume that `InfoWarning` is at least `1` (which is not a good idea, but never mind). This was causing problems when I tried to add `testinstall.g` to Travis.
Additionally, I fixed a string, and removed a redundant line.

Add SEMIGROUPS.StopTest() to standard/semieunit.tst

---

gap/attributes/attr.gi
gap/attributes/properties.gd
tst/standard/attr.tst
tst/standard/attract.tst
tst/standard/display.tst

If a semigroup has commuting idempotents, then its idempotent generated subsemigroup is commutative, and is therefore a band. In other words, it's a semilattice.
We should set this information if we already know that the semigroup has commuting idempotents (for instance, if it's any partial perm semigroup).

Set `IdempotentGeneratedSubsemigroup` to be a semilattice, if possible

---

gap/semigroups/semigrp.gi
tst/extreme/semigroups.tst
tst/standard/factor.tst
tst/testinstall.tst

This removes some diffs in the GAP manual examples that occur when the Semigroups package is loaded. As a result of this change, I had to change some of the Semigroups package tests, but not many.
Additionally, for GeneratorsOfInverseSemigroup, we always add the One if the semigroup does not have easily comparable elements (we never added it before - which was a bug). When we're adding the One, we add it to the end of the list of GeneratorsOfInverseMonoid, rather than to the beginning, to resolve some diffs.

Make changes to remove diffs in GAP tests and manual examples

---

scripts/travis-test.sh

We should run some of the GAP tests so that we make sure we're not breaking things in GAP when the Semigroups package is loaded. As a start, we can try running testinstall.g. In the future, maybe we'd want to consider running more of the GAP tests or manual examples.
This will fail until my related PR to GAP is merged, and my related PR to Semigroups is merged, and this is either merged in, or rebased on top of that.

Run testinstall.g from GAP in the Travis setup

---

gap/tools/iterators.gi
tst/standard/semipperm.tst
tst/standard/semitrans.tst

We've long had a card on Trello about why this distinction exists:
```
gap> S := FullTransformationMonoid(7);; Elements(S);;
gap> for x in S do od; time;
1158
gap> for x in Elements(S) do od; time;
21
```
You might hope that these would take the same time.
This difference is simply related to the speed of looping over an iterator as opposed to an enumerator:
```
gap> S := FullTransformationMonoid(7);; Elements(S);;
gap> for x in S do od; time;
1158
gap> for x in Iterator(S) do od; time;
1297
gap> for x in Elements(S) do od; time;
21
gap> for x in Enumerator(S) do od; time;
20
```
For full transformation semigroups, there is (sensibly) a special method for `Iterator` for full transformation semigroups, which allows us to iterator over any full transformation semigroup, basically, no matter …

Adjust iterators for T_n and I_n

---

doc/conglatt.xml
gap/congruences/conglatt.gd
gap/congruences/conglatt.gi
tst/standard/conglatt.tst
tst/testinstall.tst

This probably should've been the case when the object was first created.  A poset of semigroup congruences is a digraph with vertices labelled by the congruences themselves.  An edge `i -> j` exists if congruence ~~`i`~~ `j` is a subrelation (a refinement) of congruence ~~`j`~~ `i`.
This is in reference to Issue #369.
**EDIT:** `i` and `j` reversed.

Make congruence poset object a digraph

---

gap/congruences/conginv.gi
gap/congruences/conglatt.gi

@ChristopherRussell was having trouble knowing how his calculation was coming along when calculating the join semilattice of a bunch of congruences he was playing with.  So I thought I'd add an info warning showing how the process is coming along:
```
gap> S := RandomSemigroup(IsTransformationSemigroup, 2, 5); Size(S);
<transformation semigroup of degree 5 with 2 generators>
59
gap> latt := LatticeOfCongruences(S);
#I  Finding principal congruences . . .
#I  at least one H-class is not a subgroup
#I  the numbers of lambda and rho values are not equal
#I  Finding joins of congruences . . .
#I  Processed cong 1 of 20 (19 remaining)
#I  Processed cong 2 of 23 (21 remaining)
#I  Processed cong 3 of 26 (23 remaining)
#I  Processed cong 4 of 28 (24 remaining)
#I  Processed cong 5 of 28 (23 …
```

Better info warnings for congruence lattices

---

doc/utils.xml
doc/z-chap02.xml
gap/tools/utils.gd
gap/tools/utils.gi
scripts/travis-test.sh

This is in reference to Issue #372, adding `SemigroupsTestAll`, a function which runs
- `SemigroupsMakeDoc`
- `SemigroupsTestStandard`
- `SEMIGROUPS.TestManualExamples`
all in one command.
If one fails, it still runs the other two.  Then it returns `true` if and only if all tests were successful.

Add SemigroupsTestAll

---

gap/semigroups/semipperm.gi
tst/standard/semipperm.tst

This adds a feature requested on a Trello card.
For a zero group over a perm group, we can get an isomorphism to a partial perm semigroup by taking an isomorphism from the perm group to a partial perm semigroup, and then adding in the empty partial perm as the zero.
This doesn't have to be over perm groups though: for any other type of group, first take an isomorphism to a perm group.

Add methods for IsomorphismPartialPermSemigroup: groups and zero groups

---

gap/semigroups/semicons.gi

(I wrote this ages ago, and never made a pull request, but I think it's a decent change to make).
I have changed the code of RectangularBandCons for a transformation semigroup, for clarity. The method still returns the same semigroup, however the code is now shorter and I believe it is much clearer what is going on (i.e. the generators are elements of the direct product of a left zero semigroup and a right zero semigroup).
The diff makes it hard to see the difference exactly, so I'll copy-paste them below.
Old:
```
L := LeftZeroSemigroup(filter, m);
R := RightZeroSemigroup(filter, n);
div := DegreeOfTransformationSemigroup(L);
deg := div + DegreeOfTransformationSemigroup(R);
gens := [];
act := function(l, r, i)
if i <= div then
return i ^ l;
else
return (i - div) ^ r + div;
fi;
end;
if m …
```

Improve the code for transformation semigroup RectangularBandCons

---

gap/attributes/properties.gi
tst/standard/properties.tst

Previously the immediate methods for `IsMonogenicSemigroup` and `IsMonogenicMonoid` called the line `CanEasilyCompareElements(S)`, for the semigroup `S`, when I actually wanted to know whether I could compare the elements of the semigroup `S`. So there was a block of code that never got executed. I fixed this (accidentally in the `master` branch), but now that the block of code is executed, it is too slow, and is causing a performance regression in `tst/standard/semitrans.tst`.
I've now made all of the appropriate changes.
Once this is merged, `stable-3.0` should be merged into `master`, and then the performance regression (that currently is only present in `master`) will be resolved.

Fix immediate monogenic methods in prop.gi

---

doc/semicons.xml
doc/z-chap09.xml
gap/semigroups/semicons.gd
gap/semigroups/semicons.gi
gap/semigroups/semimaxplus.gi
tst/standard/semicons.tst

This PR adds a `BrandtSemigroup` constructor in the same vein as `TrivialSemigroup` and chums.

Brandt semigroups

---

PackageInfo.g
README.md
gap/attributes/attract.gi
gap/attributes/properties.gi
gap/greens/grac.gi
gap/greens/gracinv.gi
gap/ideals/idealact.gi
gap/ideals/ideallam.gi
gap/main/acting.gi
gap/main/orbits.gi
gap/main/semiact.gi
gap/tools/iterators.gi
scripts/travis-build-dependencies.sh
tst/extreme/misc.tst

This is required due to changes in GAP that affected the hashing of permutations, and because Orb v4.8.0 renames `IsClosed` to `IsClosedOrbit`.

Require Orb v4.8.0

---

src/bipart.cc
src/semigroups-debug.h

I'd like to clean up the GAP src directory for GAP 4.10 (see <https://github.com/gap-system/gap/pull/1915>). However, this will break packages which directly include GAP headers other than src/compiled.h -- but luckily there are just two packages doing that, IO and semigroups. Hence this PR.
The name `src/compiled.h` is of course not very "intuitive", so I'd like to change that eventually, too (naming suggestions are welcome :-), but it'll stick around as long as packages use it.

Avoid GAP headers other than src/compiled.h

---

doc/attr.xml
gap/attributes/attr.gi
tst/standard/attr.tst

It is going to be very difficult to implement completely general methods for `MinimalSemigroupGeneratingSet` that have reasonable performance. However, I think we should still write methods that apply in special cases.
Here I've added several of those special cases. The `IndecomposableElements` attribute added in PR #347 was useful for this.
The biggest class of semigroups to which the new method applies is probably finite J-trivial semigroups.

Add some basic methods for MinimalSemigroupGeneratingSet

---

gap/elements/blocks.gi
gap/elements/boolmat.gi
gap/elements/trans.gi

This PR changes `DigraphCanonicalLabelling` to `BlissCanonicalLabelling` because of [Digraphs PR number 99](https://github.com/gap-packages/Digraphs/pull/99).

Update for Digraphs

---

scripts/travis-test.sh
tst/standard/isorms.tst

This removes some harmless diffs from `isorms.tst` that were causing Travis to fail, as noted first by @ChristopherRussell.
This also tweaks `scripts/travis-test.sh` so that it should mean that the libsemigroups tests work properly. Currently the tests are only run if the `GAP` environment variable is set, but libsemigroups doesn't set this variable.
After merging into `stable-3.0`, this needs to be merged into `master` before the libsemigroups Travis setup will work properly.

Make Travis work for Semigroups and libsemigroups

---

Makefile.am

When compiling Semigroups at the moment in either `stable-3.0` or `master`, I get the following problem:
```
Making all in src/libsemigroups
CXX      src/libsemigroups_la-blocks.lo
CXX      src/libsemigroups_la-cong.lo
CXX      src/libsemigroups_la-elements.lo
CXX      src/libsemigroups_la-semigroups.lo
CXX      src/libsemigroups_la-rws.lo
CXX      src/libsemigroups_la-rwse.lo
CXX      src/libsemigroups_la-uf.lo
CXXLD    libsemigroups.la
CXX      src/semigroups_la-pkg.lo
CXX      src/semigroups_la-converter.lo
CXX      src/semigroups_la-bipart.lo
CXX      src/semigroups_la-uf.lo
CXX      src/semigroups_la-fropin.lo
CXX      src/semigroups_la-congpairs.lo
CXX      src/semigroups_la-semigrp.lo
CXXLD    semigroups.la
cnf/install-sh -c -d ./bin/x86_64-apple-darwin13.4.0-default64 ./bin/lib
cp …
```

Adjust Makefile.am to copy recursively

---

gap/semigroups/semifp.gi
tst/standard/semifp.tst

This method applies to factorizable inverse monoids of partial perms. Method is
based on the paper Presentations of Factorizable Inverse Monoids by D. Easdown,
J. East, and D. G. FitzGerald (2004).

semifp: Add a method for IsomorphismFpSemigroup

---

gap/main/orbits.gd
gap/main/orbits.gi
tst/standard/semifp.tst

Added new method `EvaluateExtRepObjWord` to help when dealing with ExtRep objects. Reduced the three methods for `EvaluateWord` to two methods that have less restrictive filters.
EDIT: I still need to add documentation and tests

Add EvaluateExtRepObjWord change EvaluateWord

---

.travis.yml
src/bipart.h
src/congpairs.cc
src/congpairs.h
src/converter.cc
src/converter.h
src/pkg.cc
src/pkg.h
src/semigroups-debug.h
src/uf.cc

It looks like all of the travis builds are failing with:
~~~~
In file included from /usr/include/x86_64-linux-gnu/gmp.h:51:0,
from /home/travis/gap/src/integer.h:24,
from /home/travis/gap/src/compiled.h:35,
from src/semigroups-debug.h:25,
from src/pkg.h:29,
from src/pkg.cc:23:
/usr/include/c++/5/cstddef:51:11: error: ‘::max_align_t’ has not been declared
using ::max_align_t;
~~~~
this PR attempts to resolve this.

Fix travis

---

gap/tools/utils.gd
gap/tools/utils.gi

It was accidentally removed in the last merge from stable-3.0.

utils: readd SemigroupsTestAll

---

doc/conginv.xml
doc/gree.xml
doc/semiboolmat.xml
doc/semiex.xml
gap/elements/boolmat.gd

Some standard test files and some manual examples are too slow, in my opinion. For some reason, this is making the 32-bit Travis tests really slow. The 32-bit job takes over 20 minutes just to run `SemigroupsTestAll`. I'll post some timings below.
I'm going to shorten some slow-running manual examples (use smaller examples), and possibly move some standard tests to the extreme files, obviously while maintaining code coverage.

Speed up tests and manual examples

---

PackageInfo.g
gap/tools/utils.gi

CONSTRUCTORS has been removed from the GAP master branch: see https://github.com/gap-system/gap/pull/2114/commits/b597f5cbf18b89e9264d2fff4362c0c652d22270

Use IS_CONSTRUCTOR instead of CONSTRUCTORS

---

gap/congruences/cong.gi
tst/testinstall.tst

This PR fixes issue #461 by altering `NrEquivalenceClasses`.  The new version doesn't assume that singletons are included in the output of `EquivalenceClasses`, and adds to the output appropriately.  The number of equivalence classes is equal to:
```(Number of EquivalenceClasses) + (Size of semigroup) - (Sum of the sizes of EquivalenceClasses)```
I added a test to `SemigroupsTestInstall` to check it's working.

Fix issue #461 (NrCongruenceClasses)

---

doc/cong.xml
gap/congruences/congrms.gi
tst/standard/conguniv.tst

If `cong` is a congruence on a finite (0-)simple semigroup described by a linked triple (i.e. if it satisfies `IsR(Z)MSCongruenceByLinkedTriple`) then we might wish to convert it to a congruence defined by generating pairs (e.g. by using `AsSemigroupCongruenceByGeneratingPairs`).  This uses a special method for `GeneratingPairsOfMagmaCongruence`, which is installed in `congrms.gi`.
It turns out that the current method is really bad in terms of the number of pairs it spits out.  It iterates over every element of the normal subgroup `n`, and doesn't combine this in any way with the column and row operations.  This PR replaces it with an all-new, improved algorithm which avoids unnecessary work and condenses the information into as few pairs as possible.  The number of generating pairs …

Smaller generating pair sets for RMS congruences

---

src/bipart.cc

Fixes issue #444 (at least for bipartitions).

Fix a bug with bipartitions moving in memory while blocks are being assigned

---

src/fropin.cc

The `stopper` component of the Froidure-Pin data structure can be a boolean or an integer, but the kernel function using this assumed that it was always an integer. This PR fixes this issue.

Fix stopper

---

gap/attributes/attr.gi
tst/standard/attr.tst

I'm not sure why I created an immediate method for `IndecomposableElements`. This PR removes the immediate method, because of https://github.com/gap-system/gap/issues/2377. It doesn't seem to serve an important purpose. I think I just assumed that setting an empty list as an attribute was cheap.

Remove IndecomposableElements immediate method

---

gap/semigroups/grpperm.gi
tst/standard/grpperm.tst

For a semigroup, to avoid adding duplicate generators to the
range perm group.

grpperm: improve default IsomorphismPermGroup

---

Makefile.am

This (along with a patch to libsemigroups) fixes semigroups in cygwin

Fix building Semigroups on windows

---

src/pkg.cc

Check the kernel version of GAP to see which signature `GVarFilt` should have.

kernel: update to check for GAP kernel version for GVarFilt definition

---

src/pkg.cc

In GAP 4.9, the latter is an alias for backwards compatibility for the former.
Alternatively, one could replace `TBipartObjMarkSubBags` by `MarkTwoSubBags` if one was willing to reorder the content of `T_BIPART` blocks so that the two subobject pointers come first, and the C++ pointer last (instead of first).

Use MarkBag instead of MARK_BAG

---

doc/ideals.xml
doc/z-chap07.xml
gap/ideals/ideals.gd
gap/ideals/ideals.gi
tst/standard/ideals.tst

This pull request adds a new attribute for a semigroup, called `Ideals`.  An attribute with the same name already exists for rings, so I chose this name for consistency.  I've only added a method for _finite_ semigroups – I'm not sure how we would approach infinite semigroups.
An ideal is a downward closed union of D-classes.  So to find all the ideals, we first find all the D-classes, then find every possible set of pairwise incomparable D-classes.  For each set, we take an element from each class, and use these as generators for an ideal (they generate all the D-classes that lie below them).  In this way, we use the minimum possible number of generators for each ideal, since we only use one generator from each of the ideal's maximal D-classes.
It turns out the Digraphs package is quite …

Add method to find all the ideals of a semigroup

---

gap/ideals/ideals.gi

There is a method in `gap/ideals/ideals.gi` which tests the equality of an ideal and a semigroup; the test is only mathematically valid if the semigroup is finite, so this PR add this as a filter to the method.
See issue #508, which is resolved by this PR.
I can't really add a test for this; but this is tested by GAP's test `tst/testinstall/domain.tst`; see #508 again for more details.
If you'd prefer a different solution to this @james-d-mitchell then please let me know and I'll see what I can do.

Add an IsFinite filter to a method for \= for a semigroup and an ideal

---

.travis.yml
scripts/travis-test.sh

I've updated the Travis setup:
- _We now run the tests against the required version of GAP, with the required version of packages._ Whenever this job fails for non-trivial reasons, but tests with newer versions of GAP/packages pass, then we should simply increase the required versions as appropriate.
- _All but one job against GAP `stable-4.9` is now against `stable-4.10`._ I believe that there is unlikely to be another release from the `stable-4.9` branch; the next round of releases will come from `stable-4.10`. So it makes sense to move these jobs.
- _I have cleaned up `scripts/travis-test.sh`_, but not changed what tests it does. I have added a (commented out) line which runs the GAP testbugfix tests, because I might want to incorporate this in the future. But I don't want to do that …

Update Travis setup

---

gap/attributes/properties.gd

It make sense to add `IsSemigroup` to `InstallTrueMethod(IsCommutativeSemigroup, IsCommutative);` to be safe; see #519.

Require IsSemigroup in the filters for the IsCommutative TrueMethod

---

gap/ideals/ideals.gi
gap/semigroups/semigraph.gi
gap/semigroups/semirms.gi
tst/standard/grpffmat.tst
tst/standard/semitrans.tst

Some changes in GAP `master` branch mean that the ranks of certain filters have changed (see https://github.com/gap-system/gap/issues/2818), which means that some rank adjustments related to the Semigroups package are not correct. To ensure compatibility with all versions of GAP I've made some changes.
If I have done everything correctly, then the only failure in Travis will be GAP's `tst/testinstall/triviso.tst`; this should be fixed if https://github.com/gap-system/gap/pull/2819 is merged into GAP's master branch.
This will therefore basically resolve #522.

Accommodate changes in GAP affecting method ranks

---

PackageInfo.g
gap/tools/utils.gi
tst/teststandard.g

This is prompted by #517: it would be nice if the `TestFile` specified in our `PackageInfo.g` file actually ran `SemigroupsTestStandard`, which provides almost comprehensive code coverage, and runs fairly quickly, as opposed to `SemigroupsTestInstall`, which does not systematically cover the whole package. This is especially useful because @alex-konovalov uses the `TestFile` from `PackageInfo.g` in some of his automated testing.
To do so, I have created a file called `tst/testinstall.g`, which runs `SemigroupsTestStandard`. @alex-konovalov requested that we find a way to make `SemigroupsTestStandard` print the line `#I  No errors detected while testing` only once, because his testing setup cannot handle multiple occurrences of this line. This prompted me to investigate what …

Update some testing details and create teststandard.g

---

gap/ideals/ideals.gi
tst/standard/ideals.tst

`IsFactorisableInverseMonoid` applied to an ideal returned false negatives,
whenever the ideal was a factorisable inverse monoid but was not equal to its supersemigroup.

ideals: resolve Issue 530 (IsFactorisableInverseMonoid)

---

gap/fp/freeinverse.gi

This PR resolves Issue #532 by not using implementation dependent features of the free group iterator. 
Disclaimer: I haven't checked if this really resolves the issue when RCWA is loaded.

freeinverse: use non-impl. dep.  free group iterator

---

PackageInfo.g

This PR resolves Issue #537 by replacing the use of `Info` in `TestAvailability` by `LogPackageLoadingMessage( PACKAGE_WARNING, ...)`

PackageInfo: don't use Info in TestAvail.*

---

gap/attributes/properties.gi
tst/standard/freeinverse.tst
tst/standard/properties.tst

With this PR ~and an adjustment to a filter in `smallsemi` that I mentioned in https://github.com/gap-packages/Semigroups/issues/543#issuecomment-425429322~, the next release of the Semigroups package should pass in Alexander's tests where all the packages are loaded.
Not that this required me to adjust an iterator test for free inverse semigroups; @james-d-mitchell has adjusted this code and presumably the tests, so it would be best to merge this after that fix has been pushed (in case this will need rebasing).
I added `SUM_FLAGS` to the method rank of `IsOrthodoxSemigroup` so that Semigroups beats smallsemi. Ideally `1` should be enough of an adjustment to make this happen, but until the current GAP master branch, method rank stuff was broken in GAP, and this is the simplest way to …

Adjust for compatibility with all packages loaded

---

doc/z-chap10.xml
gap/attributes/isomorph.gi
gap/attributes/maximal.gi
gap/attributes/properties.gi
gap/fp/freeinverse.gi
gap/greens/gren.gi
gap/main/fropin.gi
scripts/make-deps.py
tst/standard/attr.tst
tst/standard/freeinverse.tst
tst/standard/fropin.tst

I think that this resolves Issue #536.
This PR removes the previous iterator code for free inverse semigroups. The code did not function as it was intended. If I understand it correctly it was attempting to enumerate canonical forms for elements of the free inverse semigroup, which are words of the form:
> w_1 w_1 ^ -1 w_2 w_2 ^ -1 ... w_k w_k ^ -1 u 
where w_1, w_2, ..., w_k, u are words in the free group with the same number of generators as the free inverse semigroup. The previous approach (when fixed) essentially iterated through all such expressions. Unfortunately, distinct expressions of the above form do not yield distinct elements of the free inverse semigroup. In fact, of the first 10,000 values iterated through, there were only 119 distinct elements.
In this PR, I have:
1. Fixed …

Fix iterators for free inverse semigroups (issue #536) and some new methods for free inverse semigroups

---

gap/greens/gree.gi
gap/ideals/idealact.gi
gap/semigroups/semipperm.gi
gap/semigroups/semitrans.gi
tst/testinstall.tst

I've made some adjustments so that GAP's `testinstall` tests in GAP `master` pass when all packages are loaded.
In particular,
* I've changed it so that the direct product code does not apply when the arguments all satisfy `IsGroup`.
* I've added `GreensXClassOfElement` methods that include the filter `IsFinite`, to beat the GAP library ones that we do not expect to be applied when the Semigroups package is loaded
* Sometimes, with all packages loaded, the methods for `IsSemigroupIdeal and IsRegularActingSemigroupRep` would have higher ranks than those for `IsInverseActingSemigroupRep`, even though we would want the latter to apply to ideals in that representation. I've added some `TryNextMethod` calls to avoid this problem.
Overall, the work to accommodate the fixed method ordering in …

Make method selection-related tweaks to accommodate GAP fixes

---

.travis.yml
scripts/travis-build-dependencies.sh

Travis have released their new `xenial` environment, which is a build of Ubuntu from 2016, rather than `trusty`, which is from 2014. By using this, we don't have to install loads of extra updates. In particular, `xenial` includes `gcc-5.4.0`. This makes the `.travis.yml` file a lot simpler. And the builds should now be a bit quicker because of not having to do these updates any more.
I also stop installing the profiling package in the non-coverage tests, to speed them up.

Use 'xenial' in Travis rather than 'trusty'

---

doc/attr.xml
doc/properties.xml
doc/z-chap15.xml
gap/attributes/attr.gi
gap/attributes/attrfp.gi
gap/attributes/properties.gd
gap/attributes/properties.gi
gap/semigroups/semidp.gi
tst/standard/attr.tst
tst/standard/attrfp.tst
tst/standard/properties.tst

In my viva, Nik Ruskuc pointed out that decomposable is not a good name for a semigroup `S` that satisfies `S^2 = S`. Instead, he suggested `surjective' as a better name (along with several others). It makes sense because a semigroup satisfies S^2 = S if its multiplication is surjective. This is the name that I have moved to in my PhD thesis.
Since `IsDecomposableSemigroup` was never included in a released version of the package, there should be no problems with renaming it.

Rename 'IsDecomposableSemigroup' to 'IsSurjectiveSemigroup'

---

doc/semieunit.xml
gap/main/setup.gi
gap/semigroups/semieunit.gd
gap/semigroups/semieunit.gi
tst/standard/semieunit.tst
tst/standard/setup.tst

This PR integrates McAlister triple semigroups with the acting semigroups framework. It also includes various fixes, and improvements to:
- IsomorphismSemigroup when used to find an isomorphism from an E-unitary inverse semigroup to a McAlisterTripleSemigroup.
- McAlisterTripleSemigroup - replaced a check involving IsSubgroup and AutomorphismGroup by one which checks if generators are automorphisms.
- EUnitaryInverse cover - now uses DirectProduct functionality which has recently been added to Semigroups.
It also adds various attributes of the form MTSX which are synonyms for McAlsiterTripleSemigroupX.  FInally there is now a McAlisterTripleSubsemigroup attribute and functionality for these objects.

Make McAlister triple semigroups acting

---

gap/semigroups/semipperm.gi
tst/standard/semipperm.tst

If a group of partial permutations was created without any `GeneratorsOfGroup`, eg by `S := Group([], PartialPerm([1, 2]));;`, then the `GeneratorsOfSemigroup` immediate method would return `[]`, which is incorrect.
This is what is currently causing the Travis tests to fail on `stable-3.1` and `master`.

Fix GeneratorsOfSemigroup immediate method for partial perm groups

---

doc/semidp.xml
tst/standard/semidp.tst

I have created PR https://github.com/gap-system/gap/pull/3053 for GAP, which adds additional properties that are transferred from the factors of a direct product to the direct product, at creation.
This means that, once this is merged, many direct products will know more about themselves at creation than they currently do. This means the test output in `semidp.tst` and `semidp.xml` needs to be updated. However, since we still need to support previous versions of GAP, we can't just update the files with the new output. We have to make sure that the properties are definitely computed before viewing the direct product, and showing the new output. That's why there are lots of new calls to `IsRegularSemigroup`, etc.
The tests on the `GAP stable-4.10, 64-bit` Travis job will fail until #565 is …

Update semidp.tst for compatibility with future GAP version

---

gap/attributes/attr.gi
gap/elements/elements.gi
gap/ideals/ideals.gi
tst/standard/elements.tst
tst/standard/ideals.tst

I identified some ways of the methods in the package for `IsMultiplicativeZero` and `MultiplicativeZero`, particularly in relation to ideals.
* If a semigroup `S` already knows its multiplicative zero (or knows that it doesn't have one), then `IsMultiplicativeZero(S, x)` should just test `x` against this known (non-)element.
* In `IsTrivial` for a semigroup ideal, we should check whether all the ideal generators are equal first (easy) before testing whether the unique generator is the multiplicative zero (potentially hard).
* An ideal contains a zero if and only if its parent semigroup contains the same zero – for finite or infinite semigroups. Therefore, for `IsMultiplicativeZero` for an ideal and an element, if we don't have semigroup generators for the ideal, then we can just check …

Improve methods for multiplicative zeroes

---

gap/attributes/properties.gi
tst/standard/properties.tst

Currently, an empty semigroup is set to be monogenic by an immediate method. But I don't think that it should count as monogenic: its rank isn't 1, and there exists no element inside the empty semigroup that generates the empty semigroup.
I know that we normally avoid empty semigroups, and for certain properties it's probably not very clear whether the empty semigroup has that property. But here I think it's clear so we may as well fix it.

The empty semigroup is not monogenic

---

gap/semigroups/semibipart.gi
gap/semigroups/semigrp.gi
gap/semigroups/semipbr.gi
gap/semigroups/semipperm.gi
gap/semigroups/semitrans.gi
tst/standard/semibipart.tst
tst/standard/semipbr.tst
tst/standard/semipperm.tst

This commit adds a generic operator \< for semigroups, with special versions
for transformation semigroups, pbr semigroups, and bipartitions.

semigroups: operator \<

---

src/congpairs.cc

This is the only place which currently is using EQ_INTOBJS, among
all GAP packages and the whole GAP kernel. Not using it here allows
to either remove EQ_INTOBJS from GAP, or to refactor it.

Avoid using EQ_INTOBJS

---

.gitmodules
Makefile.am
configure.ac
m4/ax_check_libsemigroup.m4
prerequisites.sh
src/bipart.cc
src/bipart.h
src/congpairs.cc
src/converter.h
src/fropin.cc
src/pkg.cc
src/semigrp.h
src/uf.cc

conditionally install libsemigroups; nothing changes if there is no external libsemigroups
known to pkg-config and matching the version test; there is an extra option `--with-included-libsemigroups` to force the use of the included library (it is needed to `make dist`
including libsemigroups). The included libsemigroups will also be used if no external one is good enough.
Dealing with libsemigroups (version check, etc) is moved into m4/ subdir macro.
`src/` prefix is removed from for libsemigroups headers `#include`'s, and `src/libsemigroups` is moved one level up the directory tree.

Conditionally install libsemigroups, and drop src/ prefix for its headers

---

gap/main/setup.gi
tst/standard/setup.tst

Fix to issue #581. `LambdaOrbSchutzGp` was giving the incorrect answer sometimes. The issue lay with the `LambdaBound` being smaller than the size of the schutz group. `LambdaBound` uses the method `ActionRank` (via `LambdaRank`) and the issue was there.

resolve issue #581: changes made to ActionRank

---

gap/elements/elements.gi
tst/standard/elements.tst

I was looking at the generic code for `SmallestIdempotentPower` (which I wrote) and I felt that it wasn't very clear, and potentially slow (when the period was much smaller than the index). So I re-wrote it, conforming more directly to the description in Howie.

Re-factor SmallestIdempotentPower

---

gap/attributes/attr.gi

I wrote this ages ago, but never made a PR. It's just a small PR.
A (known) zero is a representative of the minimal ideal; as is any element of a (known) simple semigroup. Whilst thinking about multiplicative zeroes, I always thought: why not add a method for free inverse semigroups.
Although I've not added any tests, all of the changed code has 100% code coverage.

Better pre-processing in RepresentativeOfMinimalIdeal

---

doc/properties.xml
gap/attributes/properties.gd
gap/attributes/properties.gi
gap/ideals/ideals.gi
gap/semigroups/semigraph.gi
gap/semigroups/semirms.gi

This is a sensible feature to have, in my opinion, especially since the code for it already exists pretty much as part of `IsOrthodoxSemigroup`. There is a problem: this already exists in `smallsemi`, and `IsSemigroupWithClosedIdempotents` is also declared there, so loading both packages gives the warning:
```
#I  method installed for `IsSemigroupWithClosedIdempotents` matches more than one declaration
```
What should we do about this?
1. Ignore it.
2. Move the declaration of `IsSemigroupWithClosedIdempotents` to the GAP library.
3. Not have this feature in Semigroups.

Add IsSemigroupWithClosedIdempotents

---

gap/main/fropin.gi
gap/main/orbits.gi
gap/semigroups/grpperm.gi
tst/standard/fropin.tst
tst/standard/isorms.tst
tst/standard/semibipart.tst
tst/standard/semiboolmat.tst
tst/standard/semipbr.tst
tst/standard/semipperm.tst
tst/standard/semirms.tst
tst/standard/semitrans.tst

This PR partially fixes Issue #556, by removing the implication `IsFinite and IsGroup` => `IsEnumerableSemigroupRep`.  Other such implications remain, and should be removed. The remaining implications will be removed in a more major clean up (hopefully) in the coming months.

 Fix issue 556

---

src/bipart.cc

This PR fixes Issue #608. For future reference, I only had this issue when Semigroups is compiled with optimisations on (`-O3`) and is compiled with clang. As far as I can see, the code before this change is valid and does the same thing as after this change.  It might be that the bug is elsewhere in the code, or that some part of the code has undefined behaviour, so that the optimised code is broken, while the non-optimised code is not.

kernel: fix issue 608

---

gap/elements/semiringmat.gd

This removes the warning
```
#I  method installed for Matrix matches more than one declaration
```
that we currently get at startup.
Since GAP 4.10, `lib/matobj2.gd` has had the declaration `DeclareOperation("Matrix", [IsSemiring, IsList]);`. However, in Semigroups we've got the declaration `DeclareOperation("Matrix", [IsSemiring, IsHomogeneousList]);`, and we install a method for this (and hence GAP's) declaration, which is what prompts the warning.
This PR only makes the new declaration in the Semigroups package in versions of GAP before 4.10.
Fixes #615.

Avoid redundant Matrix declaration in newer GAP versions

---

gap/main/fropin.gi
gap/semigroups/semirms.gi

and also their testers and setters. Instead use one of these:
- RowsOfReesZeroMatrixSemigroup
- RowsOfReesMatrixSemigroup
- ColumnsOfReesZeroMatrixSemigroup
- ColumnsOfReesMatrixSemigroup
- MatrixOfReesZeroMatrixSemigroup
- MatrixOfReesMatrixSemigroup
Right now, in GAP 4.11 and master branch, there are just synonyms for
the attributes they replace, but this may change in the future (namely
in order to ensure that Matrix on a single argument is a plain operation,
not an attribute, as for use as a matrix *constructor* function, it is not
desirable to have it an attribute).
My hope is that this can be merged soon. Then once a release of Semigroups with this change was made, we can change Matrix to not be an attribute anymore in the GAP master branch, for GAP 4.12 down the road; see …

Avoid using attributes Matrix, Rows, Columns

---

gap/elements/semiringmat.gi
tst/standard/semiringmat.tst

Once this PR is merged and a new version of the package is released, this should mean that https://github.com/gap-system/gap/pull/2758 can be merged, and so GAP no longer has to do 'weird' things to accommodate Semigroups.
This PR changes the Semigroups package so that, when it is loaded, it gives the first-choice method for `Matrix` for `IsSemiring, IsMatrixObj`. Previously, the method was installed only for `IsSemiring, IsHomogenousList`; but since a homogenous list in GAP 4.10 onwards automatically knows that it satisfies `IsMatrixObj` in many cases, this means that the GAP library method for `IsSemiring, IsMatrixObj` method (higher ranked) was beating the one in the Semigroups package that we really wanted to use.
This adds a Semigroups package method for `Matrix` for `IsSemiring, …

semiringmat: allow final GAP 'hack' to be removed (Matrix method)

---

gap/tools/io.gi

This is a partial fix for Issue #632, I think that this will resolve the broken test in:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11/jobs/627234005
Which I think was caused by several functions in `gap/tools/io.gi` failing to close files that they open when an error was given. This PR resolves this issue by closing such files.

io: close files when erroring

---

src/bipart.cc
src/bipart.h
src/pkg.h
src/semigrp.h

This way, #defines in libsemigroups don't affect GAP headers. For example, GAP may typedef BOOL in the future, and right now that would break Semigroups because libsemigroups #defines BOOL to something. With this patch, that problem goes away.
It also seems in general useful to have a fixed order; this way, *if* things break in either GAP or libsemigroups due to a change in the respective other, at least they will break consistently.
Motivated by https://github.com/gap-system/gap/pull/3814

Make sure to include GAP headers before libsemigroups

---

src/converter.cc
tst/standard/boolmat.tst

Prior to this PR, the following happened:
~~~~
gap> S := Semigroup([
> Matrix(IsBooleanMat,
>        [[false, true], [false, true]]),
> Matrix(IsBooleanMat,
>        [[true, false], [true, false]])]);
gap> Union2(AsList(S.2)[1], AsList(S.2)[2]);
gap> Size(S);
4
~~~~
The reason being that `Union2` converts `S.2[2]` to plist rep (from blist rep), but the converter code in the kernel assumed that it will be in blist rep. This PR removes this assumption and fixes the example above.

kernel: fix bmat converter

---

doc/boolmat.xml
doc/z-chap05.xml
gap/elements/boolmat.gd
gap/elements/boolmat.gi
gap/semigroups/semitrans.gi
tst/standard/boolmat.tst

Adds `IsTransformationBooleanMat` and improves the method for `IsomorphismTransformationSemigroup` for boolean matrix semigroups whose generators are really transformations.

Better boolmat

---

Makefile.am

The version number for libsemigroups was updated (to 1), which broken cygwin as it was hard-wired to 0.
This just copies any version number.

Copy all versions of cygsemigroups for cygwin

---

configure.ac
src/congpairs.cc
src/fropin.cc

This PR fixes the root directory of semigroups getting included in the include path.
The first commit fixes two included headers -- technically these were always wrong, but worked because lots of extra things were in the include path. The second commit stops extra include paths appearing.
Now you have renamed VERSION anyway, this might not make things any better, but it is (I hope) "neater" in the long term. it would also be nice to see if it breaks any semigroups tests, to see if this is the right idea for a fix.

Fix header includes

---

tst/standard/isorms.tst

Due to https://github.com/gap-system/gap/pull/3992, things like "1 generators" should instead be shown as "1 generator". This affects a couple of tests in the Semigroups package.
To main compatibility with older versions of GAP, we have to suppress the output, rather than just adopt the new output.

Accommodate future changed ViewStrings in GAP, in isorms.tst

---

CONTRIBUTING.md

This PR changes the style recommendation for Semigroups error messages. It is no longer a requirement for them to be prefixed by `"Semigroups:"`, but they should be helpful and point to what part of the user's prompt went wrong.

Update error message format in CONTRIBUTING.md

---

src/congpairs.cc
src/fropin.cc
src/fropin.h
src/semigrp.cc
src/uf.cc

- move `ELM_PLIST2` from fropin.h to fropin.cc
- `SET_ELM_PLIST2` called CHANGED_BAG on the wrong list (resulting in a
potential GC crash); change it to use `ASS_LIST` which avoids this and in
general will take care of everything for us at a minuscule performance cost
- in particular, this renders several calls to `RetypeBag` unnecessary
- a call to `RetypeBag(rules, T_PLIST_CYC)` was incorrect (because the
elements of `rules` actually seem to be plists, not cyclotomics); instead
use `ASS_LIST` to let the GAP kernel worry about setting suitable TNUMs
- use `ASS_LIST` and `AssPlist` in a few more places
- tiny optimization: instead of `INT_INTOBJ(expr) == 0` it is better to do
`expr = INTOBJ_INT(0)` as the compiler can precompute the right side
- drop some redundant calls to …

Revise C level access to GAP lists in fropin.cc

---

doc/isorms.xml
doc/z-chap18.xml
gap/attributes/isorms.gd
gap/attributes/isorms.gi
tst/standard/isorms.tst

This adds a few attributes for Rees (zero) matrix semigroups. Given a Rees (zero) matrix semigroup `S` the function `CanonicalMatrix` returns a matrix over `UnderlyingSemigroup(S)` which defines a Rees (zero) matrix semigroup isomorphic to `S`. This matrix is canonical in the sense that given any two isomorphic Rees (zero) matrix semigroups the function `CanonicalMatrix` will return the same matrix. `CanonicalRees(Zero)MatrixSemigroup(S)` simply returns `Rees(Zero)MatrixSemigroup(CanonicalMatrix(S), UnderlyingSemigroup(S))`.
The idea behind the method is that two Rees zero matrix semigroups M_0[G;{1 .. m}, {1 .. n};P] and M_0[G;{1 .. m}, {1 .. n};Q] are isomorphic if and only if they lie in the same orbit of the set of all m x n matrices over G_0 with respect to the group action of …

Add CanonicalMatrix and CanonicalRees(Zero)MatrixSemigroup

---

prerequisites.sh

@mtorpey I think this resolves issue #702, but can you please double check before we merge it? 
Also @wilfwilson is it the intended behaviour that every line of output from `prerequisites.sh` has the prefix `-e`?

prerequisites: fix line 25

---

README.md

- point to travis-ci.com instead of .org (which will be turned off on December 31, 2020)
- adjust the badge to point to the stable-3.4 branch
If you have other active branches (`master`?) you may want to apply similar changes there?

README.md: fix Travis link and badge

---

src/converter.cc

I noticed while reviewing #708 that we can get ride of the special case here. The minimum version of GAP required by Semigroups is currently 4.9.0.

Remove special case for GAP < 4.9, which is no longer supported

---

PackageInfo.g

My location details were out of date. I prefer to leave them out now, rather than update them. I also prefer to be credited with my middle initial.

Update Wilf's details in PackageInfo.g

---

README.md
prerequisites.sh
src/converter.cc
src/semigrp.cc

Use of IMMUTABLE is an internal kernel detail, and there are some plans
to eventually move it from a bit in the TNUM to a separate object flag
at some point.

Replace some uses of IMMUTABLE

---

.github/workflows/GAP.yml

I've got a working version of #717, because my PRs there were merged. You can either merge this PR, or close it and take the code for use in #717. I just thought it would be easiest for you to get the code this way.
It wasn't completely simple to add GAP `stable-4.10` support (some of the packages contained in `bootstrap-pkg-full` for GAP 4.10 are too old for this package, so would have to be manually replaced), so I haven't done that.
All this does is run `tst/teststandard.g`, which runs `SemigroupsTestStandard()`. If you want it to do more (e.g. compile the manual, test the manual examples, run `SemigroupsTestInstall`, run extreme tests) then I recommend you make a file `tst/testall.g` analogous to the one in the Digraphs package to do what you want.

ci: add more actions (working)

---

doc/isorms.xml

Two of these were given warnings of the kind:
```
#I Writing manual.six file ...
#I Finally the HTML version . . .
#I First run, collecting cross references, index, toc, bib and so on . . .
#I Table of contents complete.
#I Producing the index . . .
#I Writing bibliography . . .
#I Second run through document . . .
#W WARNING: non resolved reference: rec(
Attr := "IsUnderlyingSemigroup" )
#W WARNING: non resolved reference: rec(
Attr := "Matrix" )
```
And another reference to `Matrix` was referring to the wrong `Matrix` in the GAP documentation.

Fix broken references in the documentation

---

tst/standard/isomorph.tst
tst/standard/isorms.tst

In a future GAP version, "1 generators" will change to "1 generator", and so to maintain forwards and backwards compatibility we should hide the output. It's inconsequential in these examples anyway.

Suppress incorrect "1 generators" in test output

---

prerequisites.sh

This should make the file more robust.
* I've added `#!/bin/bash` to the top
* I've put some stuff in quotes
* I've removed the `-e` from the `echo` calls, where possible
* If the `libsemigroups/.VERSION` file is now missing (which might happen accidentally; see #740), the file now attempts to recreate it using the `libsemigroups/etc/version-number.sh` file. This should hopefully never be needed, but why not add it? Previously this script would fail if the `libsemigroups/.VERSION` file was missing.

Improve the prerequisities.sh file

---

gap/main/fropin.gi
tst/standard/fropin.tst

This just apes the functionality for ```AsListCanonical```.
In theory all of this should be replaced soon anyway!

add EnumeratorCanonical for enumerable semigroups without generators

---

doc/cong.xml
gap/congruences/cong.gi
tst/standard/cong.tst
tst/standard/congpairs.tst
tst/testinstall.tst

Allows `EquivalenceRelationLookup` and `EquivalenceRelationCanonicalLookup` to be applied to equivalence relations.
I didn't really examine the current setup very hard for subtleties and there should probably be more functions this is done to, hence the draft. Should possibly `TryNextMethod` instead of `Error` as well.

Extend congruence methods to equivalence relations

---

.github/workflows/ci.yml

GAP `stable-4.10` includes too-old versions of datastructures, digraphs, and images. We get around this by cloning the repositories for these packages.

Test against GAP stable-4.10 on GitHub Actions

---

prerequisites.sh

This was a bad idea (my bad idea); if you are using a git version of libsemigroups, then this file will be created once if you run `prerequisites.sh`, but then never updated, even when you pull a new version of libsemigroups. So the `.VERSION` file will eventually become out of date, and then the Semigroups package won't compile (because it thinks its libsemigroups version is too old, even when it isn't). There's no need to create this file, so let's just not do it.

prerequisites.sh: do not create libsemigroups/.VERSION

---

doc/semicons.xml
doc/z-chap09.xml
gap/main/fropin.gi
gap/semigroups/semicons.gd
gap/semigroups/semicons.gi
tst/standard/semicons.tst

_This PR supersedes #673; I've started a new one to squash the current log of ~30 commits and have easier write access to the PR (I was previously submitting PRs to Murray's branch)._
This PR is joint work with @james-d-mitchell, @MTWhyte and @reiniscirpons. It creates a new `StrongSemilatticeOfSemigroups` object initialised from a list of semigroups, a (meet-semilattice) digraph and a list of homomorphisms. Currently element enumeration, element comparison and multiplication is possible, which makes this a fully working **Semigroups** object, and it will be ready to merge as soon as it passes tests and review.
In future I will also be working off this branch to create additional features such as decomposition of certain types of completely regular semigroups into …

Strong Semilattice of Semigroups

---

gap/attributes/attr.gd
gap/semigroups/semidp.gd

In GAP versions before 4.12, these are only declared for `IsGroup`.  This means that we have to separately declare them for `IsSemigroup`.  This then gives warnings when further methods are installed for `IsGroup`, (e.g. if you load the polycyclic package after loading Semigroups) because they don't know which declaration they belong to.  Not a huge problem, but one with an easy fix.
The GAP master branch does, and GAP 4.12 will, declare these things for `IsSemigroup` instead – see https://github.com/gap-system/gap/pull/4329. Therefore we should only make these declarations when GAP has not already made them.  Eventually, the package will presumably require GAP 4.12, and so all of this code can be deleted. I have added comments to that effect.
It turns out that the repeated declaration of …

Only declare `DirectProductOp`/`SmallGeneratingSet` when required

---

PackageInfo.g
ci/docker-install-deps.sh
ci/docker-test.sh
gap/doc.g
gap/tools/utils.gd
gap/tools/utils.gi
makedoc.g

This resolves the issues I mentioned in #767, with the same solution that I have used for Digraphs.
The reason I've had to touch `PackageInfo.g` and `ci/docker-install-deps.sh` is to make sure that the CI uses GAPDoc at least v1.6.3. This version of GAPDoc adds the option `nopdf` to `MakeGAPDocDoc`.
If you call `MakeGAPDocDoc` without the `nopdf` option, and if `pdflatex` is not available, then `MakeGAPDocDoc` fails to create a `manual.six` file. Thus running `GAPDocManualLabFromSixFile` in this situation will fail. Moreover, the Docker containers used in the CI do not have `pdflatex` available.
I think the reason why this wasn't failing previously is because we weren't compiling the manuals in the Azure Pipelines tests. I have added compilation of the manuals to the tests in this PR. If …

Make compilation of manuals more robust

---

.release

Now that #745 has been resolved, it's no longer necessary to build and clean the Semigroups package in the `.release` script, in order to build the manual.
Also, when we fix links in the documentation, I've made the `sed`s a bit more robust and/or general-purpose (in my opinion). In particular, I don't require the package directories to include a version number in their name (`pkgname-version`), and the search is now case-insensitive. Therefore `/pkg/GAPDoc-1.6.3/`, `pkg/GAPDoc/`, `/pkg/gapdoc-1.6.3/`, and `/pkg/gapdoc/` all get replaced.

Update the `.release` script

---

doc/semifp.xml
doc/z-chap10.xml
gap/semigroups/semifp.gd
gap/semigroups/semifp.gi
tst/standard/semifp.tst

This PR adds a new implementation of [`ElementOfFpSemigroup`](https://www.gap-system.org/Manuals/doc/ref/chap52.html#X847012347856C55E) from the main GAP distribution. The original implementation needs the first argument to be an element family, and the second to be an associative word. For ease of use, I thought it might be helpful to have a shorthand that can take an fp semigroup as the first argument. That way, you get reasonable output rather than an error when running the final line of this example:
```
gap> f := FreeSemigroup("x", "y");;
gap> AssignGeneratorVariables(f);
#I  Assigned the global variables [ x, y ]
gap> s := f / [[x * x, x], [y * y, y]];
<fp semigroup on the generators [ x, y ]>
gap> a := ElementOfFpSemigroup(s, x * y);
x*y
```
I also added the corresponding …

Allow ElementOfFpSemigroup to take simpler args

---

.github/workflows/ci.yml
tst/teststandard.g

I hadn't realised that we weren't already doing this.
Also add a comment, don't try to build two packages (genss and images) that can't be built.

Run `SemigroupsTestInstall` and `TestManualExamples` in the GitHub Actions CI

---

gap/elements/ffmat.gi
tst/testinstall.tst

`ImmutableMatrix` is a GAP function that can change its argument in place, even if it is given an immutable argument. In particular, `ImmutableMatrix` can change the representation of the matrix that it is given.
For us, this is dangerous since matrices in different representations are considered to be *not* equal in GAP, and they cannot in general be multiplied. Therefore, if a matrix that belongs to a semigroup has its representation changed in-place, then multiplication and equality testing no longer necessarily work correctly in that semigroup. This is what led to the issue in #788, where a semigroup of size 16 had 17 elements, because it had two copies of its identity in different representations.
An even safer version would be to change the line to:
```
mat := …
```

Copy the matrix argument given to `NewMatrixOverFiniteField`

---

configure.ac
m4/ax_check_libsemigroup.m4
m4/ax_pthread.m4

This stops newer autoconf versions from complaining about them

Stop using obsolete autoconf macros

---

configure.ac
src/pkg.cc

This allows future GAP versions to drop it (although 4.12 definitely will support it). As far as I could tell, `SYSTEM_IS_32_BIT` is not used anywhere, so I just removed it. Likewise, `SYS_IS_CYGWIN32` was unused, so I also removed it while at it.

Avoid using SIZEOF_VOID_P

---

doc/main.xml
doc/tietze.xml
doc/z-chap10.xml
doc/z-chap19.xml
doc/z-chap20.xml
doc/z-chap21.xml
doc/z-chap22.xml
doc/z-chap23.xml
gap/doc.g
gap/fp/tietze.gd
gap/fp/tietze.gi
init.g
read.g
tst/standard/tietze.tst

Authors: Ben Spiers (@bspiers) and Tom Conti-Leslie (@tomcontileslie)
**Ready for review**
This PR creates methods for a "semigroup Tietze" object which contains the generators and relations of an fp semigroup. Tietze transformations can be manually applied to the object to change the presentation, giving an fp semigroup isomorphic to the original. The idea is to also have a "SimplifyPresentation" operation which will intelligently apply transformations in order to reduce the overall length of the presentation.
Once transformations have been applied to the Tietze object to taste, it can be converted back into an fp semigroup and a mapping object can be produced which provides an isomorphism between the original fp semigroup and the modified version.

Tietze transformations for semigroups

---

configure.ac
src/pkg.cpp

[This was added to `stable-3.4` in #790 but didn't make its way into 4.0.0].
From @fingolfin's commit:
> This allows future GAP versions to drop it (although 4.12 definitely will support it). As far as I could tell, `SYS_IS_CYGWIN32` was unused, so I removed it while at it.

Avoid using `SIZEOF_VOID_P`

---

gapbind14/include/gapbind14/gap_include.hpp

There is no reason to include gmp.h here. This makes compiling Semigroups a tad easier for e.g. people who have GMP installed via Homebrew on an M1 mac (e.g. me :-) ) where this is not found without adding the right compiler flags manually to CPPFLAGS

Remove spurious dependency on libgmp

---

gap/elements/semiringmat.gi
tst/standard/elements/semiringmat.tst

... by using TryNextMethod in Matrix() methods instead of raising an error
Together with https://github.com/gap-system/gap/pull/4833 by @hulpke this should resolve the conflict between GAP master and semigroups. So if we this patch is acceptable for you, then as soon as there is a semigroups release with it, we could merge that GAP PR and finally release GAP 4.12 -- well, after some more testing, obviously! But thanks to the work done on https://github.com/gap-system/PackageDistro we will also (again) get tests of Semigroups (and all other distributed GAP packages) against GAP master, so we can deal with those, too

Improve compatibility with GAP's MatrixObj project

---

.github/workflows/ci.yml
configure.ac
m4/ax_check_hpcombi.m4

I noticed that the GitHub Actions CI jobs spend ~50% of their time (e.g. 6 minutes out of 12) compiling C/C++ code. This patch attempts to reduce that by combining the GH Actions caching feature with https://ccache.dev to reduce the compiler overhead to just a few seconds for most builds -- only builds were the C++ sources actually changed would take longer.
However this feature does not mesh well with `-march=native`, which anyway causes other problems e.g. for distro packagers. I've thus also removed this from the default FLAGS. If you think this goes to far, one could also try to modify `.github/workflows/ci.yml` to build w/o `-march=native`.
Note that the performance benefit (if any) of course only shows up once the caches are primed.

Use ccache to speed up CI builds (and don't use `-march=native` by default)

---

doc/conglatt.xml
gap/congruences/conglatt.gi
tst/standard/congruences/conglatt.tst

This PR fixes an issue relating to the ordering of congruences in `CongruencesOfSemigroup` and in the nodes of the associated `LatticeOfCongruences`, before this change (and after v4.0.0) they didn't agree:
~~~
gap> S := InverseSemigroup(PartialPerm([1, 3], [2, 4]),
>                          PartialPerm([1], [1]));;
gap> D := DigraphReflexiveTransitiveReduction(LatticeOfRightCongruences(S));
<immutable digraph with 22 vertices, 49 edges>
gap> S := InverseSemigroup(PartialPerm([1, 3], [2, 4]),
>                          PartialPerm([1], [1]));;
gap> D := DigraphReflexiveTransitiveReduction(LatticeOfRightCongruences(S));
<immutable digraph with 22 vertices, 49 edges>
gap> x := DigraphSinks(D)[1];
2
gap> NrEquivalenceClasses(RightCongruencesOfSemigroup(S)[x]);
7
~~~
when the correct value …

conglatt: fix ordering issue

---

doc/attr.xml
doc/greens-generic.xml
doc/z-chap10.xml
gap/attributes/attr.gd
gap/attributes/attr.gi
gap/greens/froidure-pin.gi
gap/greens/generic.gd
gap/greens/generic.gi
tst/standard/attributes/attr.tst
tst/standard/greens/froidure-pin.tst

We already have `PartialOrderOfDClasses` and `MaximalDClasses`; it would be nice if we had similar for `L` and `R`. It would be useful for my code to do with direct products, in particular.
I've added methods for enumerable semigroups. I feel like it should be simple to do something clever for acting semigroups, but maybe not.
I still need to polish this PR (more manual examples and tests), so it's not ready to be merged, but I'm creating this PR to spur me to finish it, and possibly as a way to ask for advice.

Add support for partial orders of L/R-classes

---

doc/attrinv.xml
gap/semigroups/semipperm.gi
tst/standard/semigroups/semipperm.tst

The issue seems to have been caused by there being mismatch in the
generators used in `SmallerDegreePartialPermRepresentation`, so that
`Factorization` used too large indices

semipperm: resolve issue 817

---

src/froidure-pin-fallback.cpp

The inner plist is modified, so we must invoked `CHANGED_BAG` on it, not the outer one.
Or just use the safe function `ASS_LIST` instead of `SET_ELM_PLIST`...

Fix GC bug in SET_ELM_PLIST2

---

.gitignore
gapbind14/demo/.gitignore
gapbind14/demo/Makefile.gappkg
gapbind14/demo/Makefile.in
gapbind14/demo/configure

Update `.gitignore` to allow adding the missing `Makefile.in` & `configure`, then update `Makefile.gappkg` to the latest version.
Also remove the added support for `.cpp` from `Makefile.gappkg`, for two reasons:
1. using an identical copy of the original `Makefile.gappkg` makes future updates easier (of course it is perfectly acceptable to submit a PR to GAP to add support for the `.cpp` extension into the master copy of `Makefile.gappkg`!)
2. referencing a relative path like `../src/gapbind14.cpp` in `KEXT_SOURCES` messed up the code which attempts to adapt paths so that all object files end up inside the `gen` directory. It is easier and safer to just copy the source file into the local `src` directory; and if one does that anyway, one may as well rename it on the fly
Of course I am …

Fix gapbind14/demo

---

Makefile.am

Copying new builds of loadable modules, shared libraries or executable
over an existing older copy confuses macOS' code signing system, leading
to segfaults when trying to load the updated copy. As a workaround,
delete the old copy before copying the new file into place.

Add a workaround for macOS code signing issues.

---

gap/attributes/homomorph.gi
tst/standard/attributes/homomorph.tst

An unhelpful error was given by `SemigroupIsomorphismByImages` when it should have returned `fail`. This PR fixes this issue.

homomorph: fix issue in SemigroupIsoByImages

---

gap/attributes/isomorph.gi
gap/attributes/isorms.gi

(In fact, one can set `IsBijective` in these cases.)

set `IsInjective` flag before calling `SetNiceMonomorphism`

---

gap/attributes/isomorph.gi
gap/attributes/isorms.gi
gap/libsemigroups/froidure-pin.gi
tst/standard/libsemigroups/froidure-pin.tst

The issue turned out to be caused when the number of generators is equal to the size of the fp semigroups, simple fix.

Fix issue 869

---

gap/attributes/attr.gi
tst/standard/attributes/attr.tst

The issue was that the method for `MaximalDClasses` for `IsMonoidAsSemigroup` assumed that the argument knew its `MultiplicativeNeutralElement`, which isn't the case for monoids/semigroups defined by a multiplication table.

Resolve Issue #868

---

README.md
gap/attributes/homomorph.gi
gap/libsemigroups/froidure-pin.gi
tst/standard/attributes/homomorph.tst
tst/standard/libsemigroups/froidure-pin.tst

This should resolve Issue #875

Fix the README to use the correct version of GAP that's required

---

m4/find_gap.m4

Stop referencing unused GAP_LIBS, and balance 'checking for GAP architecture' message: The conclusion to the check was not printed and hence no trailing newline printed. So whatever configure message came next ended up starting on the wrong line.

m4/find_gap.m4: update

---

gap/attributes/properties.gd
gap/attributes/properties.gi
gap/attributes/semifp.gd
gap/attributes/semifp.gi
gap/semigroups/semifp.gd
gap/semigroups/semifp.gi
init.g

This PR adds a method for `IsSelfDualSemigroup`, `AntiIsomorphismDualFpSemigroup`, and a method for `ReversedOp` for fp semigroup and fp monoid elements.
This PR is currently missing documentation and tests.

Adds method for `IsSelfDualSemigroup` and related functionality

---

gap/semigroups/semigrp.gi
tst/standard/semigroups/semigrp.tst
tst/standard/semigroups/semiquo.tst
tst/standard/semigroups/semitrans.tst

This issue was a missing method for ClosureSemigroup for non-libsemigroups types. This resolves issue #865

Fix closure semigroup for non-libsemigroups types

---

gap/attributes/translat.gi
tst/standard/attributes/translat.tst

Previously the code for computing bitranslations of a RZMS could be incorrectly be triggered by a RZMS defined with a non-regular sandwich matrix.

Fix faulty usage of 0-simple RZMS translations code

---

gap/main/setup.gi

Applying to it a matrix row (= vector) is invalid. It also is not necessary in this case.

Remove invalid MutableCopyMat invocation

---

.github/workflows/ci.yml
.github/workflows/clang-format-check.yml
.github/workflows/config-options.yml
.github/workflows/lint.yml
.github/workflows/manual.yml
doc/io.xml
doc/isomorph.xml
doc/semieunit.xml
doc/semiex.xml
environment.yml
m4/ax_check_libsemigroup.m4
prerequisites.sh
src/to_gap.hpp

Ci config options

---

CHANGELOG.md
README.md
doc/z-chap02.xml

Update libsemigroups URL

---

gap/greens/acting.gi
tst/standard/greens/acting.tst

This PR resolves issue #931, it seems that the method for `RhoOrbStabChain` for a $\mathscr{D}$-class used the wrong representative, which resulted in a false negative for membership testing in the $\mathscr{D}$-class.

greens: fix RhoOrbStabChain(DClass)

---

configure.ac

typo (ERNEL<-KERNEL) in configure.ac

---

Makefile.gappkg
Makefile.in

Resolves #928 
This is a simpler (?) alternative to PR #937 and thus closes #937 if it gets merged.
@dimpase could you verify if this also resolves the issue (modulo #938 of course) for you?

Use the C++ compiler to link semigroups.so

---

autogen.sh

Resolves #943. Alternative to #946 and hence closes #946
That issue only affects people working with the git version of Semigroups (because the release tarballs bundle the required files). So it is OK if we play a bit dirty, in this case, by invoking automake and touching install-sh. 
See also the comments inside the changes for further details.
Alternatives considered:
- just require autoconf >= 2.71 and otherwise refuse to run: excludes people who can't easily get a newer autoconf; plus there is no good clean way to check the autoconf version in a script other than to parse the output of `autoconf --version` which is not meant to be human readable
- include bundled copies of those files -- simple (we use it for GAP) but those files need to be regularly updated, and you'll get complaints …

Work around autoconf 2.69 bugs

---

gap/attributes/factor.gi
gap/attributes/isorms.gi
init.g

This PR deals with Semigroiups issue #949 which arises from GAP PR #5073. 
Declarations of the NC versions have been made in init.g 
The two methods in gap/attributes/homomorph.gi test the input so remain non-NC. 
A call in gap/attributes.factor.gi:227 has been changes to PreImagesRepresentativeNC. 
In gap/attributes/isorms.gi:329,519 calls to PreImagesRepresentative are in tester functions, so remain non-NC. 
In gap/attributes/isorms.gi:1109,1116 Methods for PreImagesRepresentative have been changed to NC. 
No changes have been made to the doc files (isorms.xml, properties.xml, z-chap14.xml).
Tests should test, so no changes made in homomorph.tst or isorms.tst.

some changes of PreImages... to NC versions

---

GNUmakefile.in
Makefile.gappkg
m4/ax_check_libsemigroup.m4

... between using a bundled and an external libsemigroups

buildsys: unify rpath handling

---

GNUmakefile.in

This supports GAP's latest build system, with no libtool when building on Cygwin. I left in support for older GAPs, by putting the dll in the right place in that case too.

Support GAP on Cygwin with libtool removed

---

.github/dependabot.yml

I've noticed warnings at e.g. https://github.com/semigroups/Semigroups/actions/runs/7628515256 node12 versus nod16 etc. etc. due to the use of the outdated `codecov/codecov-action@v2`. Using Dependabot helps avoid this by ensuring GH Actions are always used in their most up-to-date version.

Set up Dependabot to update GitHub Actions

---

gap/attributes/attr.gi
tst/standard/attributes/attr.tst

Running `IrredundantGeneratingSubset` with a set of 2 generators of a cyclic semigroup currently causes issues, e.g.
```
gap> IrredundantGeneratingSubset([Transformation([2, 1]), IdentityTransformation]);
Error, Usage: cannot create a semigroup with no generators ...
gap> IrredundantGeneratingSubset([Transformation([ 1, 1, 3, 1 ]), Transformation([3, 3, 1, 3 ])]);
Error, Usage: cannot create a semigroup with no generators ...
```
What seems to happen is that the generating set gets reduced to only have 1 generator, but for some reason the check for irredundancy still gets carried out, meaning that we attempt to generate a semigroup with empty generating set, hence the error.
My fix adds a condition in the if statement that causes the error. Not sure this addresses the underlying issue …

Fix bug in `IrredundantGeneratingSubset`

---

src/pkg.cpp

T_BIPART consists of a general pointer not managed by GAP's GC, plus two bag references (which may be NULL). Hence we can use MarkAllButFirstSubBags instead of a custom marking function.
This prepares Semigroups for <https://github.com/gap-system/gap/pull/5662>, but also works in previous GAP versions.

Use MarkAllButFirstSubBags for T_BIPART

---

.github/workflows/ci.yml

Install libtool via brew in the macosx ci job.

ci: install libtool for macosx

---

etc/code-coverage-test-gap.py

This PR fixes the GAP coverage script on certain platforms. The issue seems to be caused by feeding raw `\n` newlines into `gap`, as a fix we add non-raw newlines after the `_GAP_COMMANDS` are created.
Once accepted, these changes should also be propagated to the `Digraphs` package, since it uses an identical script.

Fix GAP coverage script newline issue

---

PackageInfo.g
init.g

As part of GAP Days 2024, we're working on https://github.com/gap-system/gap/issues/5761. This PR will address the `Semigroups` part of that issue.

Better kernel module checking

---

gap/congruences/conginv.gi

The bug is that `pairs` can be unassigned if the congruence is trivial.

Fix bug in gen pairs

---

gapbind14/include/gapbind14/to_cpp.hpp
src/to_cpp.hpp

There are actually six TNUMs indicating strings.
I don't know which branch you want this to land in. I based this branch
on tag v5.4.0 so you should be able to re-target this PR if it should
go into `stable-5.4` instead of `main`.

Use GAP kernel helper IS_STRING_REP to test for strings

---

gapbind14/include/gapbind14/to_gap.hpp

This is the last place using it in the GAP ecosystem :-) 🥳

Avoid obsolete C_NEW_STRING macro

---

gap/tools/display.gi
tst/standard/tools/display.tst

This PR fixes an issue in `TikzString` for bipartitions, that crept in at some point.

Fix `TikzString` for bipartitions

---

PackageInfo.g
doc/semipperm.xml
doc/z-chap11.xml
environment.yml
gap/elements/pperm.gd
gap/elements/pperm.gi
gap/semigroups/semipperm.gi

This PR adds an operation `UniformRandomPartialPerm` that returns a partial perm acting on `n` points  uniformly at random. On the down side this is slower than `RandomPartialPerm` but on the up side the distribution is uniform. 
This requires documentation and test.
Joint work with @le27 and Alex Levine.

Add `UniformRandomPartialPerm`

---

GNUmakefile.in
doc/isomorph.xml
gap/attributes/isomorph.gi
src/isomorph.cpp
src/isomorph.hpp
src/pkg.cpp
tst/standard/attributes/isomorph.tst

This PR
- introduces a new function ``PermuteMultiplicationTable(temp, table, p)``, implemented in C, which permutes a multiplication table ``table`` and stores the result by changing ``temp`` in-place.
- refactors ``OnMultiplicationTable`` to call ``PermuteMultiplicationTable``.
I wasn't sure where to put the function, so I added a new file.

PermuteMultiplicationTable, refactor OnMultiplicationTable, add docs

---

doc/attr.xml
doc/maxplusmat.xml
doc/z-chap11.xml
gap/greens/acting.gi
gap/main/setup.gd
gap/main/setup.gi

Add `OnePseudoInverseOfSemigroupElement` method for more types

---

gapbind14/include/gapbind14/gapbind14.hpp
gapbind14/src/gapbind14.cpp
src/pkg.cpp

This will improve compatibility with GCC 15 and future GAP versions.
For background see <https://github.com/gap-system/gap/pull/6010> and <https://github.com/gap-system/gap/issues/5857>
This is targeting `main` right now but I am happy to retarget it to your preferred branch.

Replace custom type `GVarFunc` with GAP's `ObjFunc`

---

.github/workflows/config-options.yml
.github/workflows/extended.yml
.github/workflows/standard.yml

It doesn't seem to be needed any more, as in, not having it there isn't causing any crashes.

Stop adding `-pthread` to `LDFLAGS` in the GitHub Actions CI

---

.github/workflows/clang-format-check.yml
.github/workflows/codespell.yml
.github/workflows/config-options.yml
.github/workflows/extended.yml
.github/workflows/manual.yml
.github/workflows/standard.yml
.github/workflows/workspaces.yml

I think dependabot will have already done this in the `main` branch. But I'm making all of these changes on the `stable-5.5` branch.

Update GitHub Actions workflows to use `actions/checkout@v5`

---

.github/workflows/config-options.yml
.github/workflows/extended.yml
.github/workflows/manual.yml
.github/workflows/standard.yml

~I've added pull requests #1113, #1114, #1115, and #1116, all of which contain commits from this pull request.~
~Once those are merged, I'll rebase this pull request and mark it as ready for review, at which point it should have a rather smaller diff.~
The main thing to note is that `gap-actions/setup-gap@v3`, unlike `v2`, no longer clones or builds the packages that we want to be cloned or built. So we have to do it ourselves now.
To see that the updated "Extended tests" workflow works properly (it won't run here since it isn't set to run on pull requests), see https://github.com/wilfwilson/Semigroups/actions/runs/17761920802

Update the CI workflows to use the latest versions of the `gap-actions` tools

---

.github/workflows/config-options.yml
.github/workflows/standard.yml

The code coverage hasn't been working properly for a while, but we didn't notice. This should fix things and make it so that we notice any future problems more quickly.

CI: use the token to upload coverage data to Codecov, and fail if the `codecov/codecov-action` action doesn't work

---

doc/bibliography.xml
doc/cartan.xml
doc/z-chap11.xml
gap/attributes/cartan.gd
gap/attributes/cartan.gi
gap/greens/acting.gi
init.g
read.g
tst/standard/attributes/cartan.tst

This PR add several functions which allow for the computation of the character table of a monoid and the Cartan matraix of a monoid which satisfy IsActingSemigroups. The current implementation is close to the original implementation of [Balthazar Charles](https://github.com/ZoltanCoccyx).

Add Cartan matrix computation for monoids
