doc/chap2.xml, doc/chap4.xml, doc/examples.xml, doc/semigroups.bib, gap/attributes.gi, gap/examples.gd, gap/examples.gi, tst/examples.tst
Some minor tweaks to @n-ham's PR. I'll merge this if the travis tests run ok.
=> Ham examples

doc/cong.xml, scripts/travis-test.sh, tst/standard/boolmat.tst, tst/standard/conglatt.tst
Various things were wrong with the tests, including some failed tests not being detected by Travis.  This should fix everything, and Travis should go green.
The only thing I'm not sure about is my change to `boolmat.tst`.  `FullBooleanMatMonoid(2)` seems to have changed from 4 generators to 3.  I assumed that this wasn't important and suppressed the output - is that the right thing to do?
=> Correct the tests in the TC branch

gap/congruences/congrees.gi
After a few suggestions by Wilf, I've modified the `IsReesCongruence` function to eliminate some pointless work.
=> Improve IsReesCongruence

src/ufdata.cc
I've implemented several of James's suggestions here.  Note that the output of `UF_BLOCKS` is supposed to have holes in it, so `T_PLIST_TAB` is not appropriate.  `nullptr` can be included, and indicates where a hole should be.
=> UF_BLOCKS: improve performance

doc/attrinv.xml, tst/standard/attrinv.tst
This PR adds complete code coverage for attrinv.gi
Due to Issue #237, one of the tests is giving an incorrect answer. Therefore the tests on this PR will fail until the issue is resolved.
=> Complete code coverage for attrinv.gi

doc/bipart.xml, doc/z-chap03.xml, gap/elements/bipart.gd, gap/elements/bipart.gi, tst/standard/bipart.tst
In Issue #146, James East requests functions for computing the domain and codomain of a bipartition. This PR introduces such functions, with documentation and tests.
=> Introduce DomainOfBipartition and CodomainOfBipartition (Issue #146)

doc/maxplusmat.xml, doc/semimaxplus.xml, doc/semiringmat.xml, doc/z-chap05.xml
Some linking issues resolved, as well as adding doc for `Is...MatrixMonoid`.
=> Document matrix monoids (etc.)

doc/main.xml, doc/semigroups.bib, doc/z-chap03.xml
I've reviewed the beginning of the chapter on bipartitions. My changes mostly focuses on the multiplication, and on what it means for a partition to be annular.
The previous definition of multiplication was incorrect.
=> Update bipartition documentation: multiplication and annular

doc/semipbr.xml, doc/z-chap03.xml
A couple of minor things, which together clear up some errors in `SemigroupsMakeDoc`.
=> Fix semipbr doc

doc/display.xml, doc/z-chap18.xml
=> WIP Add some small bits of missing doc

doc/blocks.xml, doc/trans.xml, doc/z-chap03.xml, doc/z-chap13.xml, gap/elements/blocks.gi, gap/tools/utils.gi
Added documentation for functions `CanonicalTransformation` and `CanonicalBlocks`. Also removed an unused variable from the code of `CanonicalBlocks`.
=> Added documentation for CanonicalTransformation and CanonicalBlocks

doc/display.xml, doc/fropin.xml, doc/main.xml, doc/maxplusmat.xml, doc/semiact.xml, doc/semiex.xml, doc/z-chap01.xml, doc/z-chap03.xml, doc/z-chap05.xml, doc/z-chap06.xml, doc/z-chap08.xml, doc/z-chap13.xml
This PR replaces #300 and depends on PR #304.
=> Document acting and enumerable semigroups

doc/freeband.xml, doc/z-chap10.xml
Added documentation for the functions ContentOfFreeBandElement, IsFreeBandElementCollection, and IsFreeInverseSemigroupElementCollection.
=> Documentation for ContentOfFreeBandElement

doc/semitrans.xml, doc/z-chap13.xml, gap/semigroups/semitrans.gi
This replaces Julius's PR, but hopefully fixed to pass the Travis tests, and also adds a reference to `IsConnectedDigraph` from the Digraphs package.
=> doc: added IsConnectedTransformationSemigroup

doc/utils.xml, doc/z-chap06.xml
We surely don't need to wait for Travis to run on this PR - it is super innocuous. I eagerly await your thoughts.
=> doc: update DefaultOptionsRec

Makefile.am, configure.ac, m4/ax_pthread.m4, src/pkg.cc
This pull request hopefully fixes Issue #328.
=> Fix issue 328

gap/attributes/attract.gi, tst/testinstall.tst
=> Fix issue 330

doc/utils.xml, doc/z-chap02.xml
=> Document SemigroupsTestExtreme

doc/bipart.xml, doc/z-chap03.xml
This needed documenting, as per #298.
=> doc: add IntRepOfBipartition

doc/z-chap06.xml, gap/main/setup.gi, tst/standard/semigrp.tst
=> Fix issue 336

gap/elements/semiringmat.gd, gap/elements/semiringmat.gi, gap/semigroups/semimaxplus.gd, gap/semigroups/semimaxplus.gi, tst/standard/semiringmat.tst
This PR resolves Issue #352 about there being a name clash with some of the HomAlg packages.
=> Random matrix

PackageInfo.g
=> Add subtitle to PackageInfo.g

gap/attributes/attract.gi, tst/standard/attract.tst
This PR attempts to resolve issue #366, in the way indicated on that issue.
=> Improve MultiplicativeNeutralElement for ideals

gap/attributes/properties.gi, tst/standard/cong.tst, tst/standard/congpairs.tst, tst/standard/semiquo.tst, tst/standard/semirms.tst, tst/testinstall.tst
Resolves #377 
The changed test output is as a result of semigroups now knowing that they are non-regular.
=> Fix IsInverseSemigroup

README.md, doc/z-chap02.xml
=> Add comment about compilers and C++11

gap/main/semiact.gi, gap/semigroups/semiboolmat.gi, gap/semigroups/semigrp.gi, src/semigrp.cc, tst/standard/semigrp.tst
This PR fixes Issue #424 (factorisation returned incorrect answers) and cleans up a couple of further issues that fixing this highlighted.
=> Fix issue 424

gap/attributes/maximal.gi, tst/extreme/maximal.tst
This is a minor change that reduces duplicated work.
=> Efficiency improvements to maximal subsemigroups

gap/semigroups/semigrp.gi, tst/testinstall.tst
This PR hopefully resolves Issue #435
=> Fix issue 435

PackageInfo.g, README.md, gap/tools/utils.gi, scripts/travis-coverage.py
This PR updates the test infrastructure for Semigroups to be more like that of Digraphs. Some redundant or unused functions are removed in the process.
=> Update tests infrastructure

gap/attributes/properties.gi, tst/testinstall.tst
This PR resolves Issue 459, as indicated in the issue itself.
=> prop: resolve Issue 459 IsTrivial

gap/semigroups/semicons.gi, gap/semigroups/semimaxplus.gi, gap/tools/utils.gi
This PR resolves Issue #463 by replacing `EvalString` by `ValueGlobal`, as suggested by @fingolfin.
=> Resolve Issue #463: EvalString -> ValueGlobal

gap/semigroups/semieunit.gi
=> Fix the hash function for McAlister triple semigroup elements

m4/ac_find_gap.m4
Sorry if this is on the wrong branch; please let me know if you want it on another
=> Update m4/ac_find_gap.m4 to latest version

scripts/travis-build-dependencies.sh
This should clear up the problems that we've been having. See also https://github.com/gap-packages/Digraphs/pull/130.
=> travis: fix problem with cURL

src/pkg.cc
I based this PR on stable-3.0, let me know if I should do something different.
=> Two C code tweaks: don't use InfoBags; use AlwaysNo for IsMutableObjFuncs

PackageInfo.g
=> Use full names instead of initials in PackageInfo.g

PackageInfo.g
Since I'm at a different university now, I thought it made sense to adjust my details in `PackageInfo.g`.
=> Update Wilf's details in PackageInfo.g

gap/greens/gree.gi
See #531.
I can't really add tests for this.
=> Bump ranks of GreensXClassOfElement methods

gap/semigroups/semirms.gi, gap/tools/io.gi, tst/standard/semirms.tst
=> Add pickling of Rees (0-)matrix semigroups

CHANGELOG.md, CONTRIBUTING.md
This is a good start I think. Please merge and continue the work @james-d-mitchell because I don't have time for any more
=> Update CONTRIBUTING and CHANGELOG for v3.1.0

PackageInfo.g
This is PR is almost identical to #578, but the linting should pass (I only added a single space before the comment that @fingolfin added).
=> PackageInfo: add license

.gitignore, Makefile.am, configure.ac, gap/main/setup.gi, m4/ax_check_libsemigroup.m4, prerequisites.sh, src/bipart.cc, src/bipart.h, src/congpairs.cc, src/converter.h, src/fropin.cc, src/pkg.cc, src/semigrp.h, src/uf.cc, tst/standard/setup.tst
A cherry pick of recent commits to `master` that should be in `stable-3.1`.
=> Cherry pick

.travis.yml, scripts/travis-build-dependencies.sh, scripts/travis-build-semigroups.sh, scripts/travis-test.sh
=> travis: configure with --with-external-libsemigroups

doc/new_bibliography.xml
Fix one reference, and add more details to another.
=> bib: update very slightly

gap/elements/ffmat.gi, gap/elements/semiringmat.gd, gap/elements/semiringmat.gi, tst/standard/ffmat.tst, tst/standard/semiringmat.tst
See individual commit messages for more details; there shouldn't be anything controversial.
=> Some matrix element related cleanup

gap/attributes/attr.gi, gap/greens/grac.gi, gap/greens/gree.gi, tst/standard/grac.tst
=> grac: add error to IsoPermGroup

src/semigrp.cc
This fix was somehow left out of PR #645. This fixes the issues highlighted by @fingolfin.
=> kernel: fix error macro

doc/boolmat.xml, gap/elements/boolmat.gi, tst/standard/boolmat.tst
=> Fix bug in IsRowTrim / IsColTrim for boolean matrices

.travis.yml, gap/tools/utils.gi
This is another attempt to resolve Issue #634.
=> Add GASMAN("collect") to SEMIGROUPS.StopTest

tst/standard/gree.tst
Hopefully this PR increases the code coverage of `gree.gi` sufficiently to allow the CI to pass.
=> gree: increase code coverage

.travis.yml
Same as https://github.com/gap-packages/Digraphs/pull/310.
=> Travis: build all branches except release candidates

gap/congruences/congpairs.gi, src/congpairs.cc, tst/testinstall.tst
=> congpairs: fix for non-trivial classes

.codecov.yml
@james-d-mitchell You'll need to turn on codecov integration at codecov.io to make this work I think.
=> Add codecov configuration file

CHANGELOG.md, LICENSE, PackageInfo.g, README.md, doc/display.xml, doc/main.xml, doc/new_bibliography.xml, doc/semigrp.xml, doc/title.xml, doc/z-chap02.xml, gap/attributes/isomorph.gi, gap/attributes/isorms.gi, gap/attributes/properties.gi, gap/elements/maxplusmat.gi, gap/elements/pbr.gd, gap/elements/pbr.gi, gap/elements/semiringmat.gd, gap/elements/semiringmat.gi, gap/semigroups/semimaxplus.gi, m4/find_gap.m4, src/fropin.cc, tst/standard/semiringmat.tst
As described by the commit messages:
* Update some peoples' URLs
* `doc/main.xml`: update some package URLs
* Change `http`→`https` where possible
* `properties.gi`: can not → cannot
* `semigrp.xml`: update Log "1 generators → 1 generator"
* Use standard Markdown syntax for links
* Remove checks concerning GAP versions < 4.10
* Fix weird whitespace issue
* The linter (locally on my computer) was saying that the second character in this lines was not spaces. Even though it looked like a space. So I replaced it with an actual space.
=> Various small technical tweaks

.github/workflows/ci.yml, .github/workflows/cpplint.yml, Makefile.am, etc/cpplint.sh, etc/gaplint.sh
This separates the linting fixes in PR #748 into a separate branch, as requested @wilfwilson
=> ci: fix linting

gap/semigroups/semifp.gi, tst/standard/semifp.tst
=> Method for AssignGeneratorVariables for fp semigroups and monoids

.github/workflows/ci.yml, tst/standard/isomorph.tst
This should address the immediate problem in #771, but we don't really know why...
=> Fix GitHub Actions CI

CHANGELOG.md
James's name lacked the usual `[brackets]` in the rendered version. Also a style tweak that I prefer.
=> Tiny tweak to `CHANGELOG.md`

.github/workflows/lint.yml, src/congpairs.cc, src/converter.cc, src/converter.h, src/fropin.cc, src/semigrp.cc
=> Fix warnings from cpplint-1.5.5

gap/congruences/conglatt.gi, gap/semigroups/semipperm.gd, gap/semigroups/semipperm.gi, tst/standard/semigroups/semipperm.tst
=> semipperm: allow SmallerDegree for other types

gap/congruences/congsemigraph.gi, tst/standard/congruences/congsemigraph.tst
=> congsemigraph: add meet method

doc/dual.xml, gap/attributes/dual.gd
=> make IsDualSemigroupRep not a representation

.github/workflows/release.yml, ci/run-gap-testextreme.g, gap/attributes/properties.gi, tst/testextreme.g
This was indeed related to the commit indicated in #880
=> Resolve issue 880

m4/ax_check_hpcombi.m4
An attempt to resolve #894, @jengelh does this resolve the issue in the Semigroups package at least?
=> Change `-march=avx` -> `-mavx`

tst/standard/attributes/properties.tst, tst/standard/attributes/translat.tst, tst/standard/semigroups/semipperm.tst
=> Adjust tests to work with old and new GAP

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/manual.yml, .github/workflows/release.yml
- codespell: correct spelling
- Update some build system files to their latest versions
- ci: Bump gaplint -> 1.1.3
- Ensure SEMIGROUPS.UniversalFakeOne is in filter IsComponentObjectRep
- Remove invalid MutableCopyMat invocation
- Adjust tests to work with old and new GAP
- Update some GH actions to latest
=> Update some GH actions to latest

doc/greens-generic.xml, gap/greens/acting.gi, tst/standard/greens/acting.tst
=> greens: fix bug in RightGreensMultiplier for acting semigroups

src/to_gap.hpp
Hopefully this will resolve #996, although this won't be checked by the CI.
=> Resolve Issue #996 (u_int32_t -> uint32_t)

.mailmap, PackageInfo.g
=> Update Joe's info

read.g
=> Don't try to read non-existent file

doc/attr.xml
=> fix typo in nambooripad partial order documentation

gap/main/setup.gi
=> Fix ChooseHashFunction rank issue.

gap/attributes/properties.gd
Work towards resolving issue #1013, companion to https://github.com/gap-packages/smallsemi/pull/45
=> Generalize IsSelfDualSemigroup declaration

.mailmap, PackageInfo.g
I am not sure which branch to target with this; let me know and
I can rebase and retarget this PR on something other than `main`.
=> Update my contact details

tst/extreme/semirms.tst, tst/extreme/translat.tst, tst/standard/attributes/isorms.tst, tst/standard/attributes/translat.tst, tst/standard/main/froidure-pin.tst, tst/standard/semigroups/semirms.tst, tst/standard/tools/io.tst
Motivated by 
https://github.com/gap-system/gap/issues/2434
=> Remove SmallGroup in tests
